import { z } from 'zod';
import { orderStatusSchema, paymentMethodSchema, paymentStatusSchema } from './order';
import { userRoleSchema } from './account';
export const managedUserSchema=z.object({id:z.string(),name:z.string(),email:z.string().email(),role:userRoleSchema,isActive:z.boolean(),createdAt:z.string(),updatedAt:z.string()});
export const createManagedUserSchema=z.object({name:z.string().trim().min(2).max(200),email:z.string().trim().email(),password:z.string().min(8).max(200),role:userRoleSchema.default('CUSTOMER')});
export const updateUserRoleSchema=z.object({role:userRoleSchema});
export const updateUserStatusSchema=z.object({isActive:z.boolean()});
export const managedUserQuerySchema=z.object({page:z.coerce.number().int().positive().default(1),pageSize:z.coerce.number().int().positive().max(100).default(25),q:z.string().trim().optional(),role:userRoleSchema.optional(),isActive:z.enum(['true','false']).transform(v=>v==='true').optional()});
export const auditActionSchema=z.enum(['PRODUCT_FAMILY_CREATED','PRODUCT_FAMILY_UPDATED','PRODUCT_CREATED','PRODUCT_UPDATED','PRODUCT_ARCHIVED','PRODUCT_PUBLISHED','PRODUCT_DELETED','COLORWAY_DELETED','PRODUCT_BULK_DELETED','PRODUCTS_HIDDEN','PRODUCTS_SHOWN','VARIANT_CREATED','VARIANT_UPDATED','INVENTORY_UPDATED','MEDIA_UPLOADED','MEDIA_DELETED','MEDIA_REORDERED','BRAND_CREATED','BRAND_UPDATED','BRAND_DELETED','COLOR_CREATED','COLOR_UPDATED','ORDER_STATUS_CHANGED','ORDER_CANCELLED','USER_CREATED','USER_ROLE_CHANGED','USER_DISABLED','USER_ENABLED','USER_DELETED','ANNOUNCEMENT_UPDATED','ANNOUNCEMENT_ENABLED','ANNOUNCEMENT_DISABLED']);
export const auditLogSchema=z.object({id:z.string(),actorUserId:z.string(),actorRole:userRoleSchema,actor:z.object({name:z.string(),email:z.string().email()}),action:auditActionSchema,entityType:z.string(),entityId:z.string().nullable(),metadata:z.record(z.string(),z.unknown()).nullable(),createdAt:z.string()});
export const auditLogQuerySchema=z.object({page:z.coerce.number().int().positive().default(1),pageSize:z.coerce.number().int().positive().max(100).default(25),actorUserId:z.string().optional(),actorRole:userRoleSchema.optional(),action:auditActionSchema.optional(),entityType:z.string().optional()});
export type CreateManagedUserInput=z.infer<typeof createManagedUserSchema>;export type ManagedUserQuery=z.infer<typeof managedUserQuerySchema>;export type AuditAction=z.infer<typeof auditActionSchema>;export type AuditLogQuery=z.infer<typeof auditLogQuerySchema>;
export const updateOrderStatusSchema = z.object({ status: orderStatusSchema });
export const adminOrderSortSchema = z.enum(['newest', 'oldest', 'total_desc', 'total_asc']);
export const adminOrderQuerySchema = z.object({ page: z.coerce.number().int().positive().default(1), pageSize: z.coerce.number().int().positive().max(100).default(25), q: z.string().trim().max(320).optional(), orderNumber: z.string().trim().optional(), email: z.string().trim().optional(), status: orderStatusSchema.optional(), paymentStatus: paymentStatusSchema.optional(), paymentMethod: paymentMethodSchema.optional(), dateFrom: z.coerce.date().optional(), dateTo: z.coerce.date().optional(), sort: adminOrderSortSchema.default('newest') });
export const inventoryUpdateSchema = z.object({ stockQuantity: z.coerce.number().int().nonnegative() });
const slug = z.string().trim().min(2).max(100).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/);
export const createBrandSchema = z.object({ name: z.string().trim().min(2).max(100), slug, isActive: z.boolean().default(true) });
export const updateBrandSchema = createBrandSchema.partial().refine((v) => Object.keys(v).length > 0);
export const createColorSchema = z.object({ name: z.string().trim().min(2).max(100), slug, hex: z.string().regex(/^#[0-9a-fA-F]{6}$/).nullable().optional(), isActive: z.boolean().default(true) });
export const updateColorSchema = createColorSchema.partial().refine((v) => Object.keys(v).length > 0);
export const reorderMediaSchema = z.object({ items: z.array(z.object({ id: z.string().cuid(), position: z.number().int().nonnegative(), isPrimary: z.boolean().optional() })) });
const productFamilyIdsSchema=z.array(z.string().cuid()).min(1).max(100).refine(ids=>new Set(ids).size===ids.length,'Product family IDs must be unique');
export const bulkProductFamiliesSchema=z.object({productFamilyIds:productFamilyIdsSchema});
export const bulkProductVisibilitySchema=bulkProductFamiliesSchema.extend({visible:z.boolean()});
export type BulkProductFamiliesInput=z.infer<typeof bulkProductFamiliesSchema>;export type BulkProductVisibilityInput=z.infer<typeof bulkProductVisibilitySchema>;
export type AdminOrderQuery = z.infer<typeof adminOrderQuerySchema>;
