'use client';
import type { OrderStatus } from '@footwear/database';
import type { OrderDetail } from '@footwear/shared';
import { ChevronRight, MoreHorizontal } from 'lucide-react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import React, { type KeyboardEvent, type MouseEvent, useState } from 'react';
import { formatBDT } from '@/components/catalog/product-card';
import { DownloadInvoiceButton } from '@/components/orders/download-invoice-button';
import { adminApi, type AdminOrderListItem } from '@/lib/admin-api';
import { orderTransitions } from './order-actions';

export function OrderStatusBadge({status}:{status:OrderStatus}){const tone=status==='PENDING'?'border-neutral-500 bg-neutral-100 text-neutral-950':status==='DELIVERED'?'border-neutral-300 bg-white text-neutral-700':status==='CANCELLED'?'border-neutral-300 bg-neutral-200 text-neutral-600':'border-neutral-300 bg-neutral-50 text-neutral-800';return <span className={`inline-flex border px-2 py-1 text-[10px] font-semibold tracking-[.08em] ${tone}`}>{status}</span>}

function RowActions({order,onUpdated}:{order:AdminOrderListItem;onUpdated:(order:OrderDetail)=>void}){
  const router=useRouter(),[pending,setPending]=useState<OrderStatus|null>(null),[error,setError]=useState('');
  async function transition(label:string,status:OrderStatus){if(status==='CANCELLED'&&!confirm(`Cancel order ${order.orderNumber}? Inventory will be returned to stock.`))return;setPending(status);setError('');try{const updated=await adminApi.status(order.orderNumber,status);onUpdated(updated);router.refresh()}catch{setError(`Could not ${label.toLowerCase()}.`)}finally{setPending(null)}}
  return <details className="relative" onClick={event=>event.stopPropagation()}><summary className="flex h-9 w-9 cursor-pointer list-none items-center justify-center border border-[var(--line)] bg-white hover:bg-neutral-100" aria-label={`Actions for ${order.orderNumber}`}><MoreHorizontal size={18}/></summary><div className="absolute right-0 z-20 mt-1 w-52 border border-[var(--line)] bg-white p-1 shadow-sm"><Link className="block px-3 py-2 text-sm hover:bg-neutral-100" href={`/admin/orders/${order.orderNumber}`}>View order</Link>{orderTransitions[order.status].map(([label,status])=><button className="block w-full px-3 py-2 text-left text-sm hover:bg-neutral-100 disabled:opacity-50" disabled={pending!==null} key={status} onClick={()=>void transition(label,status)}>{pending===status?`${label}…`:label}</button>)}{order.confirmedAt&&<div className="border-t border-[var(--line)] px-3 py-2"><DownloadInvoiceButton admin orderNumber={order.orderNumber}/></div>}{error&&<p className="border-t border-[var(--line)] px-3 py-2 text-xs text-red-700" role="alert">{error}</p>}</div></details>
}

const customer=(order:AdminOrderListItem)=>({name:order.shippingRecipient||order.contactName,phone:order.shippingPhone||order.contactPhone});

export function AdminOrderList({orders}:{orders:AdminOrderListItem[]}){
  const router=useRouter(),[rows,setRows]=useState(orders);
  const updated=(order:OrderDetail)=>setRows(current=>current.map(row=>row.orderNumber===order.orderNumber?{...row,status:order.status,confirmedAt:order.confirmedAt}:row));
  const open=(order:AdminOrderListItem)=>router.push(`/admin/orders/${order.orderNumber}`);
  const onRowClick=(event:MouseEvent,order:AdminOrderListItem)=>{if((event.target as HTMLElement).closest('a,button,details,summary'))return;open(order)};
  const onRowKey=(event:KeyboardEvent,order:AdminOrderListItem)=>{if(event.key==='Enter')open(order)};
  if(!rows.length)return <div className="border border-[var(--line)] bg-white px-5 py-16 text-center"><h2 className="text-base font-semibold">No orders found</h2><p className="mt-2 text-sm muted">Try changing the status, search, or date filters.</p></div>;
  const action=(order:AdminOrderListItem)=><RowActions order={order} onUpdated={updated}/>;
  return <><div className="hidden border border-[var(--line)] bg-white md:block"><table className="w-full table-fixed text-left text-sm"><thead className="border-b border-[var(--line)] bg-[#eeeeea]"><tr><th className="w-[16%] px-3 py-3">Order</th><th className="w-[23%] px-3 py-3">Customer</th><th className="w-[12%] px-3 py-3">Date</th><th className="w-[14%] px-3 py-3">Status</th><th className="w-[14%] px-3 py-3">District</th><th className="w-[13%] px-3 py-3 text-right">Total</th><th className="w-[8%] px-3 py-3 text-right">Actions</th></tr></thead><tbody>{rows.map(order=>{const person=customer(order);return <tr className={`cursor-pointer border-b border-[var(--line)] transition-colors last:border-0 hover:bg-neutral-50 ${order.status==='PENDING'?'bg-neutral-100/80':''}`} key={order.orderNumber} onClick={event=>onRowClick(event,order)} onKeyDown={event=>onRowKey(event,order)} role="link" tabIndex={0}><td className="px-3 py-3.5 font-semibold">{order.orderNumber}</td><td className="px-3 py-3.5"><span className="block truncate font-medium">{person.name}</span><span className="mt-0.5 block truncate text-xs muted">{person.phone}</span></td><td className="px-3 py-3.5 text-xs">{new Date(order.createdAt).toLocaleDateString('en-BD')}</td><td className="px-3 py-3.5"><OrderStatusBadge status={order.status}/></td><td className="truncate px-3 py-3.5">{order.shippingCityDistrict}</td><td className="px-3 py-3.5 text-right font-semibold">{formatBDT(order.total)}</td><td className="px-3 py-3.5"><div className="flex justify-end">{action(order)}</div></td></tr>})}</tbody></table></div><div className="grid gap-2 md:hidden">{rows.map(order=>{const person=customer(order);return <article className={`border border-[var(--line)] p-4 ${order.status==='PENDING'?'bg-neutral-100':'bg-white'}`} key={order.orderNumber}><div className="flex items-start justify-between gap-3"><button className="min-w-0 text-left" onClick={()=>open(order)}><strong className="block">{order.orderNumber}</strong><span className="mt-1 block truncate text-sm">{person.name}</span><span className="mt-0.5 block text-xs muted">{person.phone}</span></button><OrderStatusBadge status={order.status}/></div><div className="mt-4 flex items-end justify-between gap-4 border-t border-[var(--line)] pt-3"><div><span className="block text-xs muted">{order.shippingCityDistrict} · {new Date(order.createdAt).toLocaleDateString('en-BD')}</span><strong className="mt-1 block">{formatBDT(order.total)}</strong></div><div className="flex items-center gap-2">{action(order)}<Link className="flex h-9 w-9 items-center justify-center border border-[var(--line)]" href={`/admin/orders/${order.orderNumber}`} aria-label={`View ${order.orderNumber}`}><ChevronRight size={17}/></Link></div></div></article>})}</div></>;
}
