'use client';
import React,{ FormEvent,useState } from 'react';
import type { Taxonomy } from '@/lib/admin-api';
import { adminApi } from '@/lib/admin-api';
import { BlockingLoader } from './blocking-loader';
const slugify=(name:string)=>name.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
export function TaxonomyManager({kind,initial}:{kind:'brands'|'colors';initial:Taxonomy[]}){
 const[items,setItems]=useState(initial);const[message,setMessage]=useState('');const[isError,setIsError]=useState(false);const[name,setName]=useState('');const[isCreating,setIsCreating]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(isCreating)return;const d=new FormData(e.currentTarget),trimmedName=name.trim();setIsCreating(true);setMessage('');setIsError(false);try{const item=await adminApi.taxonomy(kind,{name:trimmedName,slug:slugify(trimmedName),isActive:true,...(kind==='colors'?{hex:d.get('hex')||null}:{})});setItems(v=>[...v,item]);setName('');setMessage(`${trimmedName} created.`)}catch(error){setIsError(true);setMessage(error instanceof Error?error.message:'Could not create this item.')}finally{setIsCreating(false)}}
 async function edit(item:Taxonomy){const name=prompt('Brand name',item.name)?.trim();if(!name)return;try{const updated=await adminApi.updateBrand(item.id,{name,slug:slugify(name)});setItems(values=>values.map(value=>value.id===item.id?updated:value));setMessage(`${name} updated.`)}catch(error){setMessage(error instanceof Error?error.message:'Could not update this brand.')}}
 async function toggle(item:Taxonomy){try{const updated=await adminApi.updateBrand(item.id,{isActive:!item.isActive});setItems(values=>values.map(value=>value.id===item.id?updated:value));setMessage(`${item.name} ${updated.isActive?'enabled':'disabled'}.`)}catch(error){setMessage(error instanceof Error?error.message:'Could not update this brand.')}}
 async function remove(item:Taxonomy){if(!confirm('Delete brand?\n\nProducts using this brand will remain in the catalog with no brand assigned.'))return;try{await adminApi.deleteBrand(item.id);setItems(values=>values.filter(value=>value.id!==item.id));setMessage(`${item.name} deleted. Products were preserved.`)}catch(error){setMessage(error instanceof Error?error.message:'Could not delete this brand.')}}
 return <><BlockingLoader visible={kind==='brands'&&isCreating} title="Creating brand…" message="Adding the brand to your catalog."/><div className="mt-8 grid gap-6 lg:grid-cols-[1fr_22rem]"><div className="bg-white"><ul className="divide-y divide-[var(--line)]">{items.map(item=><li className="flex items-center justify-between gap-3 p-4" key={item.id}><div className="flex items-center gap-3">{item.hex&&<span className="h-5 w-5 rounded-full border" style={{background:item.hex}}/>}<strong>{item.name}</strong><span className={`status ${item.isActive?'success':''}`}>{item.isActive?'Active':'Inactive'}</span></div>{kind==='brands'&&<div className="flex gap-2"><button className="button secondary" type="button" onClick={()=>void edit(item)}>Edit</button><button className="button secondary" type="button" onClick={()=>void toggle(item)}>{item.isActive?'Disable':'Enable'}</button><button className="button secondary" type="button" onClick={()=>void remove(item)}>Delete</button></div>}</li>)}</ul></div><form className="panel bg-white" onSubmit={submit} aria-busy={isCreating}><h2 className="text-lg font-semibold">Add {kind.slice(0,-1)}</h2><label className="label mt-5">Name<input className="field" name="name" value={name} onChange={event=>setName(event.target.value)} disabled={isCreating} required/></label>{kind==='colors'&&<label className="label mt-4">Color value<input className="field h-12" name="hex" type="color" defaultValue="#000000" disabled={isCreating}/></label>}<button className="button mt-5 w-full" disabled={isCreating||!name.trim()}>{isCreating?'Creating…':'Create'}</button>{message&&<p className={`mt-3 text-sm ${isError?'text-red-700':''}`} role={isError?'alert':'status'}>{message}</p>}</form></div></>
}
