'use client';
import React, { type FormEvent, useState } from 'react';
import { superAdminApi, type ManagedUser } from '@/lib/super-admin-api';

export function UserManager({initial}:{initial:ManagedUser[]}){
  const[users,setUsers]=useState(initial),[message,setMessage]=useState(''),[pendingId,setPendingId]=useState<string|null>(null),[creating,setCreating]=useState(false);
  const replace=(updated:ManagedUser)=>setUsers(current=>current.map(user=>user.id===updated.id?updated:user));
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();if(creating)return;const form=event.currentTarget,data=new FormData(form);setCreating(true);try{const created=await superAdminApi.create({name:data.get('name'),email:data.get('email'),role:data.get('role')});setUsers(current=>[created,...current]);form.reset();setMessage('User created. A password setup link was emailed immediately.')}catch{setMessage('Unable to create user. The email may already exist.')}finally{setCreating(false)}}
  async function changeRole(user:ManagedUser,role:ManagedUser['role']){if(role==='SUPER_ADMIN'&&!confirm('Grant full Super Admin access?'))return;setPendingId(user.id);try{replace(await superAdminApi.role(user.id,role));setMessage(`${user.name}'s role was updated.`)}catch{setMessage('Unable to update this role.');}finally{setPendingId(null)}}
  async function changeStatus(user:ManagedUser){if(user.isActive&&!confirm(`Disable ${user.name}?`))return;setPendingId(user.id);try{const updated=await superAdminApi.status(user.id,!user.isActive);replace(updated);setMessage(`${user.name} ${updated.isActive?'enabled':'disabled'}.`)}catch{setMessage('Unable to update this account.')}finally{setPendingId(null)}}
  return <div className="mt-8 grid gap-6 xl:grid-cols-[1fr_22rem]"><div className="overflow-x-auto bg-white"><table className="w-full min-w-[46rem] text-left text-sm"><thead><tr className="border-b bg-[#eeeeea]"><th className="p-3">User</th><th>Role</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody>{users.map(user=><tr className="border-b" key={user.id}><td className="p-3"><strong>{user.name}</strong><span className="block muted">{user.email}</span></td><td><select className="field !w-40" value={user.role} disabled={pendingId===user.id} onChange={event=>void changeRole(user,event.target.value as ManagedUser['role'])}>{['CUSTOMER','MANAGER','SUPER_ADMIN'].map(role=><option key={role}>{role}</option>)}</select></td><td><span className={`status ${user.isActive?'success':'danger'}`}>{user.isActive?'Active':'Disabled'}</span></td><td>{new Date(user.createdAt).toLocaleDateString()}</td><td><button className="underline disabled:opacity-50" disabled={pendingId===user.id} onClick={()=>void changeStatus(user)}>{pendingId===user.id?'Updating…':user.isActive?'Disable':'Enable'}</button></td></tr>)}</tbody></table></div><form className="panel bg-white" onSubmit={create}><h2 className="text-lg font-semibold">Add user</h2>{[['name','Name'],['email','Email']].map(([name,label])=><label className="label mt-4" key={name}>{label}<input className="field" name={name} type={name==='email'?'email':'text'} required minLength={2}/></label>)}<label className="label mt-4">Role<select className="field" name="role" defaultValue="CUSTOMER"><option>CUSTOMER</option><option>MANAGER</option><option>SUPER_ADMIN</option></select></label><button className="button mt-5 w-full" disabled={creating}>{creating?'Creating…':'Create user'}</button><p className="mt-3 text-sm" role="status">{message}</p></form></div>;
}
