/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import{ConflictException}from'@nestjs/common';import{Prisma}from'@footwear/database';import{describe,expect,it,vi}from'vitest';import{AdminOrdersService}from'./admin-orders.service';
const item={id:'item-1',orderId:'order-1',productId:'product-1',variantId:'variant-1',productName:'Runner',productSlug:'runner',sku:'RUN-42',colorName:'Black',sizeEu:new Prisma.Decimal(42),sizeUk:null,sizeUs:null,unitPrice:new Prisma.Decimal(100),quantity:2,lineSubtotal:new Prisma.Decimal(200),createdAt:new Date()};
const record=(status:'PENDING'|'CONFIRMED'|'CANCELLED'='PENDING')=>({id:'order-1',orderNumber:'RAQI-1',userId:'user-1',status,paymentStatus:'UNPAID',paymentMethod:'CASH_ON_DELIVERY',currency:'BDT',subtotal:new Prisma.Decimal(200),shippingAmount:new Prisma.Decimal(60),total:new Prisma.Decimal(260),contactName:'Rafi',contactEmail:'r@example.com',contactPhone:'01712345678',shippingRecipient:'Rafi',shippingPhone:'01712345678',shippingAddressLine:'Road 1',shippingArea:null,shippingCityDistrict:'Dhaka',shippingPostalCode:null,shippingCountry:'BD',shippingMethodCode:'STANDARD',shippingMethodName:'Standard delivery',guestAccessTokenHash:null,createdAt:new Date(),updatedAt:new Date(),confirmedAt:status==='PENDING'?null:new Date(),items:[item]});
function setup(current=record(),transitioned=1){const order={findUnique:vi.fn().mockResolvedValueOnce(current).mockResolvedValue(record('CANCELLED'))},tx={order:{updateMany:vi.fn().mockResolvedValue({count:transitioned})},productVariant:{updateMany:vi.fn().mockResolvedValue({count:1})}},prisma={order,$transaction:vi.fn((callback:(value:typeof tx)=>unknown)=>Promise.resolve(callback(tx)))},confirmationEmail={send:vi.fn()},cancellationEmail={send:vi.fn()};return{service:new AdminOrdersService(prisma as never,confirmationEmail as never,cancellationEmail as never),prisma,tx,confirmationEmail,cancellationEmail}}
describe('AdminOrdersService inventory lifecycle',()=>{
 it('restores every cancelled line exactly once and emails only after the committed transition',async()=>{const{service,tx,cancellationEmail}=setup();await service.status('RAQI-1','CANCELLED');expect(tx.order.updateMany).toHaveBeenCalledWith(expect.objectContaining({where:{id:'order-1',status:'PENDING'}}));expect(tx.productVariant.updateMany).toHaveBeenCalledWith({where:{id:'variant-1'},data:{stockQuantity:{increment:2}}});expect(cancellationEmail.send).toHaveBeenCalledOnce();expect(cancellationEmail.send).toHaveBeenCalledWith(expect.objectContaining({orderNumber:'RAQI-1',status:'CANCELLED'}))});
 it('treats repeated cancellation as idempotent and does not restore or email again',async()=>{const{service,prisma,tx,cancellationEmail}=setup(record('CANCELLED'));await service.status('RAQI-1','CANCELLED');expect(prisma.$transaction).not.toHaveBeenCalled();expect(tx.productVariant.updateMany).not.toHaveBeenCalled();expect(cancellationEmail.send).not.toHaveBeenCalled()});
 it('does not restore or email when another request already changed the order status',async()=>{const{service,tx,cancellationEmail}=setup(record(),0);await expect(service.status('RAQI-1','CANCELLED')).rejects.toBeInstanceOf(ConflictException);expect(tx.productVariant.updateMany).not.toHaveBeenCalled();expect(cancellationEmail.send).not.toHaveBeenCalled()});
 it('confirms without altering stock and sends exactly one confirmation email',async()=>{const{service,tx,confirmationEmail}=setup();await service.status('RAQI-1','CONFIRMED');expect(tx.productVariant.updateMany).not.toHaveBeenCalled();expect(tx.order.updateMany).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({status:'CONFIRMED',confirmedAt:expect.any(Date)})}));expect(confirmationEmail.send).toHaveBeenCalledOnce()});
 it('does not resend when an already confirmed order is saved as confirmed',async()=>{const{service,confirmationEmail}=setup(record('CONFIRMED'));await service.status('RAQI-1','CONFIRMED');expect(confirmationEmail.send).not.toHaveBeenCalled()});
});

describe('AdminOrdersService fulfillment list',()=>{
 it('searches saved order snapshots and returns real status counts with requested sorting',async()=>{const row=record('PENDING');const order={findMany:vi.fn(),count:vi.fn(),groupBy:vi.fn()};const prisma={order,$transaction:vi.fn().mockResolvedValue([[row],1,[{status:'PENDING',_count:{status:3}},{status:'SHIPPED',_count:{status:2}}]])};const service=new AdminOrdersService(prisma as never,{send:vi.fn()}as never,{send:vi.fn()}as never);const result=await service.list({page:1,pageSize:25,q:'rafi',sort:'total_desc'});expect(order.findMany).toHaveBeenCalledWith(expect.objectContaining({orderBy:{total:'desc'},where:expect.objectContaining({OR:expect.arrayContaining([{contactName:{contains:'rafi',mode:'insensitive'}},{shippingPhone:{contains:'rafi',mode:'insensitive'}}])}),select:expect.objectContaining({shippingCityDistrict:true,shippingRecipient:true,contactPhone:true})}));expect(result.statusCounts).toMatchObject({PENDING:3,SHIPPED:2,CONFIRMED:0});expect(result.data[0]).toMatchObject({orderNumber:'RAQI-1',shippingCityDistrict:'Dhaka',total:260})});
});
