import type { Prisma } from '@footwear/database';
import type { OrderConfirmation, OrderDetail, OrderSummary } from '@footwear/shared';

export const orderInclude = { items: { orderBy: { createdAt: 'asc' as const } } } satisfies Prisma.OrderInclude;
type OrderRecord = Prisma.OrderGetPayload<{ include: typeof orderInclude }>;
const decimal = (value: { toNumber(): number } | null): number | null => value?.toNumber() ?? null;
export function mapOrderSummary(order: OrderRecord): OrderSummary { return { orderNumber: order.orderNumber, status: order.status, paymentStatus: order.paymentStatus, paymentMethod: order.paymentMethod, currency: 'BDT', subtotal: order.subtotal.toNumber(), shippingAmount: order.shippingAmount.toNumber(), total: order.total.toNumber(), createdAt: order.createdAt.toISOString() }; }
export function mapOrder(order: OrderRecord): OrderDetail { return { ...mapOrderSummary(order), contact: { name: order.contactName, email: order.contactEmail, phone: order.contactPhone }, shippingAddress: { recipientName: order.shippingRecipient, phone: order.shippingPhone, addressLine: order.shippingAddressLine, area: order.shippingArea, cityDistrict: order.shippingCityDistrict, postalCode: order.shippingPostalCode, country: order.shippingCountry }, shippingMethod: { code: order.shippingMethodCode, name: order.shippingMethodName }, items: order.items.map((item) => ({ id: item.id, productId: item.productId, variantId: item.variantId, productName: item.productName, productSlug: item.productSlug, sku: item.sku, colorName: item.colorName, sizeEu: decimal(item.sizeEu), sizeUk: decimal(item.sizeUk), sizeUs: decimal(item.sizeUs), unitPrice: item.unitPrice.toNumber(), quantity: item.quantity, lineSubtotal: item.lineSubtotal.toNumber() })) }; }
export function mapConfirmation(order: OrderRecord, guestLookupToken?: string): OrderConfirmation { return { ...mapOrder(order), ...(guestLookupToken ? { guestLookupToken } : {}) }; }
