'use client';
import type{ShoppingCart}from'@footwear/shared';import{Minus,Plus,Trash2}from'lucide-react';import Link from'next/link';import{useEffect,useRef,useState}from'react';import{formatBDT}from'@/components/catalog/product-card';import{cartApi}from'@/lib/api-client';import{publishCartQuantity}from'@/lib/cart-events';

function withQuantity(cart:ShoppingCart,id:string,quantity:number):ShoppingCart{const items=cart.items.map(item=>item.id===id?{...item,quantity,lineSubtotal:item.unitPrice*quantity,isAvailable:item.availableStock>=quantity}:item);return{items,subtotal:items.reduce((sum,item)=>sum+item.lineSubtotal,0),totalQuantity:items.reduce((sum,item)=>sum+item.quantity,0)}}

export function CartView({initial}:{initial:ShoppingCart}){const[cart,setCart]=useState(initial),[pending,setPending]=useState<string|null>(null),[error,setError]=useState(''),cartRef=useRef(cart),confirmedRef=useRef(cart),timers=useRef(new Map<string,ReturnType<typeof setTimeout>>());useEffect(()=>{cartRef.current=cart},[cart]);useEffect(()=>()=>{for(const timer of timers.current.values())clearTimeout(timer)},[]);
 function changeQuantity(id:string,quantity:number){const optimistic=withQuantity(cartRef.current,id,quantity);cartRef.current=optimistic;setCart(optimistic);publishCartQuantity(optimistic.totalQuantity);const prior=timers.current.get(id);if(prior)clearTimeout(prior);timers.current.set(id,setTimeout(()=>{timers.current.delete(id);setPending(id);setError('');void cartApi.update(id,{quantity}).then(updated=>{confirmedRef.current=updated;cartRef.current=updated;setCart(updated);publishCartQuantity(updated.totalQuantity)}).catch(()=>{cartRef.current=confirmedRef.current;setCart(confirmedRef.current);publishCartQuantity(confirmedRef.current.totalQuantity);setError('We couldnâ€™t update your cart. Available stock may have changed.')}).finally(()=>setPending(current=>current===id?null:current))},200))}
 async function remove(id:string){setPending(id);setError('');try{const updated=await cartApi.remove(id);confirmedRef.current=updated;cartRef.current=updated;setCart(updated);publishCartQuantity(updated.totalQuantity)}catch{setError('We couldnâ€™t update your cart. Available stock may have changed.')}finally{setPending(null)}}
 if(!cart.items.length)return <section className="container page text-center"><p className="eyebrow">Your bag</p><h1 className="title mt-4">Your cart is empty.</h1><p className="mx-auto mt-4 max-w-md muted">Explore the latest RAQI footwear and find a pair made for your everyday.</p><Link className="button mt-7" href="/products">Shop footwear</Link></section>;
 return <section className="container page"><p className="eyebrow">Your bag</p><h1 className="title mt-4">Shopping cart <span className="text-[var(--muted)]">({cart.totalQuantity})</span></h1>{error&&<p className="mt-5 border border-red-200 bg-red-50 p-3 text-sm text-red-800" role="alert">{error}</p>}<div className="mt-10 grid items-start gap-10 lg:grid-cols-[1fr_23rem]"><ul className="divide-y divide-[var(--line)] border-t border-[var(--line)]">{cart.items.map(item=><li className="grid grid-cols-[6rem_1fr] gap-4 py-5 sm:grid-cols-[8rem_1fr_auto]" key={item.id}><div className="product-image" style={item.thumbnail?{backgroundImage:`url(${item.thumbnail})`,backgroundSize:'cover',backgroundPosition:'center'}:undefined}/><div><Link className="font-semibold hover:underline" href={`/product/${item.productSlug}`}>{item.productName}</Link><p className="mt-1 text-sm muted">{item.color.name} · {item.sizeEu?`EU ${item.sizeEu}`:item.sizeUk?`UK ${item.sizeUk}`:`US ${item.sizeUs}`}</p><p className="mt-2 text-sm">{formatBDT(item.unitPrice)}</p>{!item.isAvailable&&<p className="mt-2 text-xs text-red-700">This quantity is no longer available.</p>}<div className="mt-4 flex items-center gap-1 sm:hidden"><Quantity item={item} pending={pending===item.id} change={changeQuantity}/></div></div><div className="col-span-2 flex items-center justify-between sm:col-span-1 sm:block sm:text-right"><div className="hidden sm:flex"><Quantity item={item} pending={pending===item.id} change={changeQuantity}/></div><p className="font-semibold sm:mt-5">{formatBDT(item.lineSubtotal)}</p><button className="mt-3 inline-flex items-center gap-1 text-xs underline" disabled={pending===item.id} onClick={()=>void remove(item.id)}><Trash2 size={13}/> Remove</button></div></li>)}</ul><aside className="panel lg:sticky lg:top-28"><h2 className="section-title">Summary</h2><div className="mt-6 flex justify-between border-b border-[var(--line)] pb-4"><span>Subtotal</span><strong>{formatBDT(cart.subtotal)}</strong></div><p className="mt-4 text-sm leading-6 muted">Shipping is calculated at checkout. Your prices and availability are confirmed by our server.</p><Link className="button mt-6 w-full" href="/checkout">Continue to checkout</Link><Link className="mt-4 block text-center text-sm underline underline-offset-4" href="/products">Continue shopping</Link></aside></div></section>}
function Quantity({item,pending,change}:{item:ShoppingCart['items'][number];pending:boolean;change:(id:string,quantity:number)=>void}){return <div className="inline-flex border border-[var(--line)]"><button className="grid h-10 w-10 place-items-center disabled:opacity-30" aria-label={`Decrease ${item.productName} quantity`} disabled={pending||item.quantity<=1} onClick={()=>change(item.id,item.quantity-1)}><Minus size={14}/></button><span className="grid h-10 min-w-9 place-items-center text-sm" aria-live="polite">{item.quantity}</span><button className="grid h-10 w-10 place-items-center disabled:opacity-30" aria-label={`Increase ${item.productName} quantity`} disabled={pending||item.quantity>=item.availableStock} onClick={()=>change(item.id,item.quantity+1)}><Plus size={14}/></button></div>}
