import {HomeProductShelf} from '@/components/catalog/home-product-shelf';
import {RandomHeroMedia,type HeroCandidate} from '@/components/home/random-hero-media';
import {listProducts} from '@/lib/api-client';
import {selectLandingProducts,selectNewArrivals} from '@/lib/home-products';
import {ArrowRight,PackageCheck,RefreshCcw,ShieldCheck,Truck} from 'lucide-react';
import Link from 'next/link';

export default async function HomePage(){
  const[catalogResult,newArrivalResult]=await Promise.all([listProducts({sort:'newest',pageSize:24}).catch(()=>null),listProducts({newArrival:true,sort:'newest',pageSize:16}).catch(()=>null)]),catalogProducts=catalogResult?.data??[],products=selectLandingProducts(catalogProducts,16),newArrivals=selectNewArrivals(newArrivalResult?.data??[],16),heroCandidates=catalogProducts.filter(product=>product.isActive&&product.primaryImageUrl).map(product=>({id:product.id,url:product.primaryImageUrl!,slug:product.slug,label:`${product.family.name} in ${product.color.name}`} satisfies HeroCandidate));
  return <main><section className="home-hero"><div className="container home-hero-grid"><div className="home-hero-copy"><p className="eyebrow">Step into excellence</p><h1>Premium Footwear<br/>For Every Move</h1><p className="home-hero-intro">Carefully selected. Comfort assured.<br/>Style that moves with you.</p><div className="home-hero-actions"><Link className="button" href="/products?gender=MEN">Shop men <ArrowRight size={15}/></Link><Link className="button secondary" href="/products?gender=WOMEN">Shop women <ArrowRight size={15}/></Link></div></div><div className="home-hero-visual"><RandomHeroMedia candidates={heroCandidates}/></div></div></section><section className="trust-strip" aria-label="Store benefits"><div className="container trust-grid">{[[PackageCheck,'100% Original','Authentic Products'],[RefreshCcw,'Easy Returns','Hassle-Free Returns'],[Truck,'Cash on Delivery','All Over Bangladesh'],[ShieldCheck,'Secure Shopping','Your Data is Safe']].map(([Icon,title,copy])=>{const Graphic=Icon as typeof Truck;return <div className="trust-item" key={title as string}><Graphic size={22} strokeWidth={1.5}/><span><strong>{title as string}</strong><small>{copy as string}</small></span></div>})}</div></section>{newArrivals.length>0&&<HomeProductShelf products={newArrivals.slice(0,10)} viewAllHref="/products?newArrival=true"/>}<section className="category-panels container" aria-label="Shop by gender"><CategoryPanel href="/products?gender=MEN" label="Men" tone="dark"/><CategoryPanel href="/products?gender=WOMEN" label="Women" tone="light"/></section>{products.length>6&&<HomeProductShelf products={products.slice(6)} title="Trending now" autoPlay={false}/>}</main>;
}

function CategoryPanel({href,label,tone}:{href:string;label:string;tone:'dark'|'light'}){return <Link className={`category-panel ${tone}`} href={href}><h2>{label}</h2><span>Shop {label} <ArrowRight aria-hidden size={15}/></span></Link>}
