import React from 'react';

function Bone({className='' }:{className?:string}){return <span aria-hidden className={`skeleton block ${className}`}/>}
const lines=(widths:string[])=>widths.map((width,index)=><Bone className={`${width} ${index?'mt-2':''} h-3`} key={index}/>);

export function ProductCardSkeleton(){return <article className="product-card min-w-0"><div className="product-image skeleton"><Bone className="absolute left-2 top-2 h-5 w-12"/></div><div className="product-card-copy"><Bone className="h-2 w-14"/><Bone className="mt-2 h-3 w-3/4"/><Bone className="mt-2 h-2.5 w-2/5"/><Bone className="mt-3 h-3 w-20"/></div></article>}

export function CatalogSkeleton(){return <><div className="catalog-breadcrumb"><div className="container py-3"><Bone className="h-2.5 w-32"/></div></div><section className="catalog-page container" aria-label="Loading catalog" aria-busy="true"><div className="catalog-layout"><aside className="catalog-sidebar"><Bone className="h-2.5 w-10"/>{lines(['w-20','w-24','w-12','w-16'])}<Bone className="mt-8 h-2.5 w-12"/>{lines(['w-20','w-16','w-24'])}</aside><div className="min-w-0"><header className="catalog-header-row"><div><Bone className="h-2.5 w-24"/><Bone className="mt-3 h-8 w-56"/></div><Bone className="h-2.5 w-16"/></header><div className="catalog-controls"><div className="hidden gap-2 lg:flex">{[20,18,20,18].map((w,i)=><Bone className={`h-10 w-${w}`} key={i}/>)}</div><Bone className="h-10 w-24 lg:hidden"/><Bone className="h-10 w-40"/></div><div className="product-grid catalog-grid">{Array.from({length:8},(_,i)=><ProductCardSkeleton key={i}/>)}</div></div></div></section></>}

export function ProductGallerySkeleton(){return <div className="pdp-gallery"><div className="pdp-thumbnail-rail"><div className="pdp-thumbnails">{Array.from({length:4},(_,i)=><Bone className="aspect-[4/3] w-full" key={i}/>)}</div></div><Bone className="pdp-main-image w-full"/><div className="pdp-thumbnail-mobile"><div className="pdp-thumbnails">{Array.from({length:3},(_,i)=><Bone className="aspect-[4/3] w-[4.5rem]" key={i}/>)}</div></div></div>}
export function ProductPurchasePanelSkeleton(){return <div className="pdp-purchase"><Bone className="h-2.5 w-20"/><Bone className="mt-4 h-9 w-4/5"/><Bone className="mt-3 h-3 w-28"/><div className="pdp-price"><Bone className="h-7 w-32"/></div><Bone className="mt-6 h-3 w-24"/><div className="mt-3 flex gap-2">{Array.from({length:3},(_,i)=><Bone className="aspect-[4/3] w-16" key={i}/>)}</div><Bone className="mt-7 h-3 w-20"/><div className="mt-3 grid grid-cols-5 gap-2">{Array.from({length:10},(_,i)=><Bone className="h-11" key={i}/>)}</div><Bone className="mt-6 h-12 w-full"/></div>}
export function ProductPageSkeleton(){return <article className="container pb-12" aria-label="Loading product" aria-busy="true"><div className="pdp-breadcrumb"><Bone className="h-2.5 w-48"/></div><div className="pdp-layout"><ProductGallerySkeleton/><ProductPurchasePanelSkeleton/></div></article>}

export function CartItemSkeleton(){return <li className="grid grid-cols-[6rem_1fr] gap-4 py-5 sm:grid-cols-[8rem_1fr_auto]"><Bone className="product-image"/><div>{lines(['w-40','w-24','w-20'])}</div><div className="col-span-2 flex items-end justify-between sm:col-span-1 sm:block"><Bone className="h-10 w-[7.5rem]"/><Bone className="mt-5 h-4 w-20 sm:ml-auto"/></div></li>}
export function CartSummarySkeleton(){return <aside className="panel"><Bone className="h-5 w-24"/><div className="mt-6 flex justify-between border-b border-[var(--line)] pb-4"><Bone className="h-3 w-16"/><Bone className="h-4 w-20"/></div><Bone className="mt-4 h-3 w-full"/><Bone className="mt-2 h-3 w-4/5"/><Bone className="mt-6 h-12 w-full"/></aside>}
export function CartSkeleton(){return <section className="container page" aria-label="Loading cart" aria-busy="true"><Bone className="h-2.5 w-16"/><Bone className="mt-4 h-9 w-56"/><div className="mt-10 grid items-start gap-10 lg:grid-cols-[1fr_23rem]"><ul className="divide-y divide-[var(--line)] border-t border-[var(--line)]">{Array.from({length:2},(_,i)=><CartItemSkeleton key={i}/>)}</ul><CartSummarySkeleton/></div></section>}

export function CheckoutSkeleton(){return <section className="checkout-page container" aria-label="Loading checkout" aria-busy="true"><Bone className="h-2.5 w-24"/><Bone className="mt-3 h-9 w-44"/><div className="checkout-layout"><div className="checkout-sections"><section className="checkout-section"><Bone className="h-5 w-32"/><div className="checkout-fields">{['','', 'checkout-full','checkout-full','','',''].map((wide,i)=><div className={wide} key={i}><Bone className="mb-2 h-2.5 w-20"/><Bone className="h-[2.65rem] w-full"/></div>)}</div></section><section className="checkout-section"><Bone className="h-5 w-40"/><div className="checkout-methods"><div><Bone className="h-3 w-28"/><Bone className="h-3 w-16"/></div><div><Bone className="h-3 w-20"/><Bone className="h-8 w-36"/></div></div></section></div><aside className="checkout-summary"><Bone className="h-5 w-28"/><div className="checkout-items">{Array.from({length:2},(_,i)=><div className="flex justify-between" key={i}><Bone className="h-3 w-36"/><Bone className="h-3 w-16"/></div>)}</div><div className="checkout-totals">{Array.from({length:3},(_,i)=><div key={i}><Bone className="h-3 w-16"/><Bone className="h-3 w-20"/></div>)}</div><Bone className="mt-6 h-12 w-full"/></aside></div></section>}

export function OrderTableSkeleton({admin=false}:{admin?:boolean}){return <div aria-label="Loading orders" aria-busy="true"><div className="hidden border border-[var(--line)] bg-white md:block"><table className="w-full table-fixed text-left text-sm"><thead className="border-b border-[var(--line)] bg-[#eeeeea]"><tr>{(admin?['16%','23%','12%','14%','14%','13%','8%']:['35%','25%','20%','20%']).map((w,i)=><th className="px-3 py-3" style={{width:w}} key={i}><Bone className="h-2.5 w-14"/></th>)}</tr></thead><tbody>{Array.from({length:6},(_,r)=><tr className="border-b border-[var(--line)]" key={r}>{Array.from({length:admin?7:4},(_,c)=><td className="px-3 py-3.5" key={c}><Bone className={`h-3 ${c===1?'w-4/5':'w-3/5'}`}/>{c===1&&<Bone className="mt-2 h-2.5 w-1/2"/>}</td>)}</tr>)}</tbody></table></div><div className="grid gap-2 md:hidden">{Array.from({length:4},(_,i)=><article className="border border-[var(--line)] bg-white p-4" key={i}><div className="flex justify-between">{lines(['w-32','w-20'])}<Bone className="h-6 w-20 rounded-full"/></div><div className="mt-4 flex justify-between border-t border-[var(--line)] pt-3"><Bone className="h-4 w-24"/><Bone className="h-9 w-20"/></div></article>)}</div></div>}

export function AdminOrdersSkeleton(){return <section aria-label="Loading admin orders" aria-busy="true"><Bone className="h-2.5 w-20"/><Bone className="mt-3 h-9 w-40"/><Bone className="mt-3 h-3 w-28"/><div className="mt-7 flex gap-3 border-b py-3">{Array.from({length:7},(_,i)=><Bone className="h-4 w-16" key={i}/>)}</div><div className="grid gap-2 border-x border-b bg-white p-3 sm:grid-cols-2 xl:grid-cols-[minmax(16rem,1fr)_9rem_9rem_11rem_auto]"><Bone className="h-10 sm:col-span-2 xl:col-span-1"/>{Array.from({length:4},(_,i)=><Bone className="h-10" key={i}/>)}</div><div className="mt-4"><OrderTableSkeleton admin/></div></section>}
export function AdminTableSkeleton(){return <section aria-label="Loading admin table" aria-busy="true"><div className="flex items-end justify-between gap-4"><div><Bone className="h-2.5 w-20"/><Bone className="mt-3 h-9 w-44"/><Bone className="mt-3 h-3 w-32"/></div><Bone className="h-10 w-32"/></div><div className="mt-7 flex gap-2 border border-[var(--line)] bg-white p-3"><Bone className="h-10 min-w-0 flex-1"/><Bone className="h-10 w-36"/><Bone className="h-10 w-24"/></div><div className="mt-4 overflow-hidden border border-[var(--line)] bg-white"><table className="admin-table"><thead><tr>{['w-28','w-36','w-24','w-20','w-16'].map((w,i)=><th key={i}><Bone className={`h-2.5 ${w}`}/></th>)}</tr></thead><tbody>{Array.from({length:7},(_,r)=><tr key={r}>{Array.from({length:5},(_,c)=><td key={c}><Bone className={`h-3 ${c===1?'w-4/5':'w-3/5'}`}/></td>)}</tr>)}</tbody></table></div></section>}
