import { headers } from 'next/headers';
import Link from 'next/link';
import { MediaManager } from '@/components/admin/media-manager';
import { ProductEditor,VariantEditor } from '@/components/admin/product-editor';
import { ProductDeletionActions } from '@/components/admin/product-deletion-actions';
import { formatBDT } from '@/components/catalog/product-card';
import { adminApi } from '@/lib/admin-api';

export default async function Page({params}:{params:Promise<{id:string}>}){const{id}=await params,h=await headers(),init={headers:{cookie:h.get('cookie')??''}};const[p,brands]=await Promise.all([adminApi.product(id,init),adminApi.brands(init)]);return <section><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="eyebrow">{p.family.name}</p><h1 className="title mt-3">Manage {p.color.name}</h1><p className="mt-2 muted">{p.title} · {formatBDT(Number(p.basePrice))}</p></div><div className="flex gap-2"><Link className="button secondary" href={`/product/${p.slug}`}>View storefront</Link><Link className="button" href={`/admin/products/new?from=${p.id}`}>Add colorway</Link></div></div><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{p.family.products?.map(s=><Link className={`panel bg-white ${s.id===p.id?'border-black':''}`} href={`/admin/products/${s.id}`} key={s.id}><div className="flex items-center justify-between"><strong>{s.color.name}</strong><span className="status">{s.isActive&&s.publishedAt?'Published':s.isActive?'Draft':'Inactive'}</span></div><p className="mt-2 text-sm muted">{s.variants.length} EU sizes · {s.variants.reduce((n,v)=>n+v.stockQuantity,0)} stock</p></Link>)}</div><div className="mt-8 grid gap-6 xl:grid-cols-[1fr_22rem]"><div className="space-y-6"><ProductEditor product={p} brands={brands}/><VariantEditor product={p}/><ProductDeletionActions product={p}/></div><aside className="panel bg-white"><h2 className="text-lg font-semibold">{p.color.name} photographs</h2><MediaManager productId={p.id} media={p.media}/></aside></div></section>}
