/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import { ConflictException, NotFoundException } from '@nestjs/common';
import { Prisma } from '@footwear/database';
import { describe, expect, it, vi } from 'vitest';
import { CheckoutService } from './checkout.service';
import { ShippingService } from './shipping.service';

const address = { recipientName: 'Rafi Ahmed', phone: '01712345678', addressLine: '12 Road 4', area: null, cityDistrict: 'Dhaka', postalCode: null, country: 'BD' };
const input = { contact: { name: 'Rafi Ahmed', email: 'RAFI@example.com', phone: '01712345678' }, shippingAddress: address, shippingMethod: 'STANDARD' as const, paymentMethod: 'CASH_ON_DELIVERY' as const, turnstileToken:'test-token' };
const product = { id: 'product-1', title: 'Runner', slug: 'runner', basePrice: new Prisma.Decimal(100), isActive: true };
const variant = { id: 'variant-1', sku: 'RUN-42', isActive: true, stockQuantity: 3, priceOverride: null as Prisma.Decimal | null, sizeEu: new Prisma.Decimal(42), sizeUk: null, sizeUs: null, color: { name: 'Black' }, product };
const cart = { id: 'cart-1', items: [{ id: 'cart-item-1', variantId: 'variant-1', quantity: 2, variant }] };
function orderRecord(data: Record<string, unknown> = {}) { return { id: 'order-1', orderNumber: 'RAQI-20260814-ABC12345', userId: null, status: 'PENDING', paymentStatus: 'UNPAID', paymentMethod: 'CASH_ON_DELIVERY', currency: 'BDT', subtotal: new Prisma.Decimal(200), shippingAmount: new Prisma.Decimal(60), total: new Prisma.Decimal(260), contactName: 'Rafi Ahmed', contactEmail: 'rafi@example.com', contactPhone: '01712345678', shippingRecipient: address.recipientName, shippingPhone: address.phone, shippingAddressLine: address.addressLine, shippingArea: null, shippingCityDistrict: address.cityDistrict, shippingPostalCode: null, shippingCountry: 'BD', shippingMethodCode: 'STANDARD', shippingMethodName: 'Standard delivery', guestAccessTokenHash: 'hash', createdAt: new Date(), updatedAt: new Date(), items: [{ id: 'order-item-1', orderId: 'order-1', productId: 'product-1', variantId: 'variant-1', productName: 'Runner', productSlug: 'runner', sku: 'RUN-42', colorName: 'Black', sizeEu: new Prisma.Decimal(42), sizeUk: null, sizeUs: null, unitPrice: new Prisma.Decimal(100), quantity: 2, lineSubtotal: new Prisma.Decimal(200), createdAt: new Date() }], ...data }; }
function setup(options: { cart?: typeof cart | null; allocated?: number; cleared?: number; savedAddress?: typeof address | null } = {}) { const tx = { customerAddress: { findFirst: vi.fn().mockResolvedValue(options.savedAddress ?? null) }, cart: { findFirst: vi.fn().mockResolvedValue(options.cart === undefined ? cart : options.cart) }, productVariant: { updateMany: vi.fn().mockResolvedValue({ count: options.allocated ?? 1 }) }, order: { create: vi.fn().mockResolvedValue(orderRecord()) }, cartItem: { deleteMany: vi.fn().mockResolvedValue({ count: options.cleared ?? 1 }) } }; const prisma = { $transaction: (callback: (value: typeof tx) => unknown) => callback(tx) }; const notifications={send:vi.fn().mockResolvedValue(undefined)}; return { tx,notifications, service: new CheckoutService(prisma as never, new ShippingService(),notifications as never) }; }
describe('CheckoutService', () => {
  it('creates a guest snapshot, applies the Dhaka fee, allocates stock, clears the cart, and notifies RAQI', async () => { const { service, tx,notifications } = setup(); const result = await service.checkout({ guestTokenHash: 'guest' }, input); expect(result.orderNumber).toMatch(/^RAQI-/); expect(result.guestLookupToken).toBeTruthy(); expect(tx.productVariant.updateMany).toHaveBeenCalledWith(expect.objectContaining({ where: expect.objectContaining({ stockQuantity: { gte: 2 } }), data: { stockQuantity: { decrement: 2 } } })); expect(tx.order.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ userId: undefined, subtotal: new Prisma.Decimal(200), shippingAmount: new Prisma.Decimal(60), total: new Prisma.Decimal(260), contactEmail: 'rafi@example.com', items: { create: expect.arrayContaining([expect.objectContaining({ sku: 'RUN-42', unitPrice: new Prisma.Decimal(100), lineSubtotal: new Prisma.Decimal(200) })]) } }) })); expect(tx.cartItem.deleteMany).toHaveBeenCalledWith({ where: { cartId: 'cart-1' } }); expect(notifications.send).toHaveBeenCalledTimes(1); expect(notifications.send).toHaveBeenCalledWith(expect.objectContaining({ orderNumber: 'RAQI-20260814-ABC12345', items: expect.any(Array) })); });
  it('links an authenticated order and accepts only its owned saved address', async () => { const { service, tx } = setup({ savedAddress: address }); await service.checkout({ userId: 'user-1' }, { ...input, shippingAddress: undefined, savedAddressId: 'address-1' }); expect(tx.customerAddress.findFirst).toHaveBeenCalledWith({ where: { id: 'address-1', userId: 'user-1' } }); expect(tx.order.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ userId: 'user-1', guestAccessTokenHash: null }) })); });
  it('rejects a foreign saved address', async () => { const { service, tx } = setup(); await expect(service.checkout({ userId: 'user-1' }, { ...input, shippingAddress: undefined, savedAddressId: 'foreign' })).rejects.toBeInstanceOf(NotFoundException); expect(tx.order.create).not.toHaveBeenCalled(); });
  it('rejects an empty cart without allocating inventory', async () => { const { service, tx } = setup({ cart: null }); await expect(service.checkout({ guestTokenHash: 'guest' }, input)).rejects.toBeInstanceOf(ConflictException); expect(tx.productVariant.updateMany).not.toHaveBeenCalled(); });
  it('rejects inactive products and variants', async () => { for (const unavailable of [{ ...variant, isActive: false }, { ...variant, product: { ...product, isActive: false } }]) { const unavailableCart = { ...cart, items: [{ ...cart.items[0]!, variant: unavailable }] }; const { service, tx } = setup({ cart: unavailableCart }); await expect(service.checkout({ guestTokenHash: 'guest' }, input)).rejects.toBeInstanceOf(ConflictException); expect(tx.productVariant.updateMany).not.toHaveBeenCalled(); } });
  it('rolls back the application flow when conditional stock allocation fails', async () => { const { service, tx } = setup({ allocated: 0 }); await expect(service.checkout({ guestTokenHash: 'guest' }, input)).rejects.toBeInstanceOf(ConflictException); expect(tx.order.create).not.toHaveBeenCalled(); expect(tx.cartItem.deleteMany).not.toHaveBeenCalled(); });
  it('rejects a cart that changes during checkout', async () => { const { service } = setup({ cleared: 0 }); await expect(service.checkout({ guestTokenHash: 'guest' }, input)).rejects.toBeInstanceOf(ConflictException); });
  it('uses the current variant override rather than client pricing', async () => { const overrideCart = { ...cart, items: [{ ...cart.items[0]!, variant: { ...variant, priceOverride: new Prisma.Decimal(125) } }] }; const { service, tx } = setup({ cart: overrideCart }); await service.checkout({ guestTokenHash: 'guest' }, input); expect(tx.order.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ subtotal: new Prisma.Decimal(250), total: new Prisma.Decimal(310) }) })); });
  it('charges the outside-Dhaka fee from a normalized district rule',async()=>{const{service,tx}=setup();await service.checkout({guestTokenHash:'guest'},{...input,shippingAddress:{...address,cityDistrict:' Chattogram '}});expect(tx.order.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({shippingAmount:new Prisma.Decimal(120),total:new Prisma.Decimal(320)})}))});
});
