import { ConflictException, NotFoundException } from '@nestjs/common';
import { Prisma } from '@footwear/database';
import { describe, expect, it, vi } from 'vitest';
import { CartService } from './cart.service';

const product = { id: 'product-1', title: 'Runner', slug: 'runner', basePrice: new Prisma.Decimal(100), isActive: true, media: [] };
const variant = { id: 'variant-1', sku: 'RUN-42', isActive: true, stockQuantity: 4, priceOverride: null, sizeEu: null, sizeUk: null, sizeUs: null, color: { name: 'Black', slug: 'black', hex: '#000000' }, product };
const cartRecord = (overrides: Record<string, unknown> = {}) => ({ id: 'cart-1', userId: null, guestTokenHash: 'guest-a', createdAt: new Date(), updatedAt: new Date(), items: [{ id: 'item-1', cartId: 'cart-1', variantId: 'variant-1', quantity: 2, createdAt: new Date(), updatedAt: new Date(), variant: { ...variant, ...overrides } }] });

describe('CartService', () => {
  it('calculates base price and subtotal on the server', async () => { const prisma = { cart: { findFirst: vi.fn().mockResolvedValue(cartRecord()) } }; const result = await new CartService(prisma as never).get({ guestTokenHash: 'guest-a' }); expect(result).toMatchObject({ subtotal: 200, totalQuantity: 2, items: [{ unitPrice: 100, lineSubtotal: 200 }] }); expect(prisma.cart.findFirst).toHaveBeenCalledWith(expect.objectContaining({ where: { guestTokenHash: 'guest-a', userId: null } })); });
  it('uses the variant price override', async () => { const prisma = { cart: { findFirst: vi.fn().mockResolvedValue(cartRecord({ priceOverride: new Prisma.Decimal(125) })) } }; expect((await new CartService(prisma as never).get({ guestTokenHash: 'guest-a' })).subtotal).toBe(250); });
  it('rejects an out-of-stock variant before creating a cart', async () => { const tx = { productVariant: { findUnique: vi.fn().mockResolvedValue({ ...variant, stockQuantity: 0 }) } }; const prisma = { $transaction: (callback: (value: typeof tx) => unknown) => callback(tx) }; await expect(new CartService(prisma as never).add({ guestTokenHash: 'guest-a' }, { variantId: 'variant-1', quantity: 1 })).rejects.toBeInstanceOf(ConflictException); });
  it('rejects a requested quantity beyond stock', async () => { const tx = { productVariant: { findUnique: vi.fn().mockResolvedValue(variant) } }; const prisma = { $transaction: (callback: (value: typeof tx) => unknown) => callback(tx) }; await expect(new CartService(prisma as never).add({ guestTokenHash: 'guest-a' }, { variantId: 'variant-1', quantity: 5 })).rejects.toBeInstanceOf(ConflictException); });
  // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
  it('increments an existing variant instead of creating a duplicate line', async () => { const tx = { productVariant: { findUnique: vi.fn().mockResolvedValue(variant) }, cart: { upsert: vi.fn().mockResolvedValue({ id: 'cart-1' }) }, cartItem: { findUnique: vi.fn().mockResolvedValue({ quantity: 2 }), upsert: vi.fn().mockResolvedValue({}) } }; const prisma = { $transaction: (callback: (value: typeof tx) => unknown) => callback(tx), cart: { findFirst: vi.fn().mockResolvedValue(cartRecord()) } }; await new CartService(prisma as never).add({ guestTokenHash: 'guest-a' }, { variantId: 'variant-1', quantity: 1 }); expect(tx.cartItem.upsert).toHaveBeenCalledWith(expect.objectContaining({ update: { quantity: 3 }, create: expect.objectContaining({ quantity: 3 }) })); });
  it('rejects an update beyond current stock', async () => { const prisma = { cart: { findFirst: vi.fn().mockResolvedValue(cartRecord()) }, cartItem: { findFirst: vi.fn().mockResolvedValue({ ...cartRecord().items[0], variant }) } }; await expect(new CartService(prisma as never).update({ guestTokenHash: 'guest-a' }, 'item-1', { quantity: 5 })).rejects.toBeInstanceOf(ConflictException); });
  it('cannot remove a foreign cart item', async () => { const prisma = { cart: { findFirst: vi.fn().mockResolvedValue({ ...cartRecord(), items: [] }) }, cartItem: { deleteMany: vi.fn().mockResolvedValue({ count: 0 }) } }; await expect(new CartService(prisma as never).remove({ guestTokenHash: 'guest-a' }, 'foreign-item')).rejects.toBeInstanceOf(NotFoundException); });
  it('removes an owned item without affecting another cart', async () => { const prisma = { cart: { findFirst: vi.fn().mockResolvedValueOnce(cartRecord()).mockResolvedValueOnce({ ...cartRecord(), items: [] }) }, cartItem: { deleteMany: vi.fn().mockResolvedValue({ count: 1 }) } }; const result = await new CartService(prisma as never).remove({ guestTokenHash: 'guest-a' }, 'item-1'); expect(prisma.cartItem.deleteMany).toHaveBeenCalledWith({ where: { id: 'item-1', cartId: 'cart-1' } }); expect(result.items).toEqual([]); });
  it('clears only the resolved current cart', async () => { const prisma = { cart: { findFirst: vi.fn().mockResolvedValue(cartRecord()) }, cartItem: { deleteMany: vi.fn().mockResolvedValue({ count: 1 }) } }; await new CartService(prisma as never).clear({ guestTokenHash: 'guest-a' }); expect(prisma.cartItem.deleteMany).toHaveBeenCalledWith({ where: { cartId: 'cart-1' } }); });
  it('merges duplicate guest lines into the customer cart and removes guest access', async () => { const guest = { id: 'guest-cart', userId: null, items: [{ variantId: 'variant-1', quantity: 2, variant: { ...variant, stockQuantity: 3 } }] }; const customer = { id: 'customer-cart', userId: 'user-1' }; const tx = { cart: { findUnique: vi.fn().mockResolvedValueOnce(guest).mockResolvedValueOnce(customer), delete: vi.fn().mockResolvedValue({}) }, cartItem: { findUnique: vi.fn().mockResolvedValue({ quantity: 2 }), upsert: vi.fn().mockResolvedValue({}) } }; const prisma = { $transaction: (callback: (value: typeof tx) => unknown) => callback(tx), cart: { findFirst: vi.fn().mockResolvedValue({ ...cartRecord(), userId: 'user-1', guestTokenHash: null, items: [] }) } }; await new CartService(prisma as never).merge({ userId: 'user-1', guestTokenHash: 'guest-a' }); expect(tx.cartItem.upsert).toHaveBeenCalledWith(expect.objectContaining({ update: { quantity: 3 } })); expect(tx.cart.delete).toHaveBeenCalledWith({ where: { id: 'guest-cart' } }); });
  it('is idempotent after the guest cart has already been merged', async () => { const tx = { cart: { findUnique: vi.fn().mockResolvedValue(null) }, cartItem: { upsert: vi.fn() } }; const prisma = { $transaction: (callback: (value: typeof tx) => unknown) => callback(tx), cart: { findFirst: vi.fn().mockResolvedValue({ ...cartRecord(), userId: 'user-1', guestTokenHash: null, items: [] }) } }; await new CartService(prisma as never).merge({ userId: 'user-1', guestTokenHash: 'guest-a' }); expect(tx.cartItem.upsert).not.toHaveBeenCalled(); });
});
