import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma, type Product } from '@footwear/database';
import type { CreateProductInput, CreateVariantInput, ProductDetail, ProductListResponse, ProductQuery, UpdateProductInput, UpdateVariantInput } from '@footwear/shared';
import { PrismaService } from '../infrastructure/prisma/prisma.service';
import { mapProduct, mapProductList, productInclude } from './products.mapper';

@Injectable()
export class ProductsService {
  constructor(private readonly prisma: PrismaService) {}

  async list(query: ProductQuery): Promise<ProductListResponse> {
    if (query.sort === 'bestsellers' || query.sort === 'rating') throw new ConflictException(`Sort '${query.sort}' is not available until its domain is implemented`);
    const variantPrice: Prisma.ProductVariantWhereInput = { isActive: true, ...(query.minPrice != null || query.maxPrice != null ? { OR: [{ priceOverride: { gte: query.minPrice, lte: query.maxPrice } }, { priceOverride: null }] } : {}) };
    const where: Prisma.ProductWhereInput = { isActive: true, category: query.category ? { OR: [{ slug: query.category }, { parent: { slug: query.category } }] } : undefined, gender: query.gender, material: query.material ? { equals: query.material, mode: 'insensitive' } : undefined, soleType: query.soleType ? { equals: query.soleType, mode: 'insensitive' } : undefined, occasions: query.occasion ? { some: { slug: query.occasion, isActive: true } } : undefined, variants: query.color || query.sizeEu || query.sizeUk || query.sizeUs || query.inStock != null ? { some: { ...variantPrice, color: query.color ? { slug: query.color, isActive: true } : undefined, sizeEu: query.sizeEu, sizeUk: query.sizeUk, sizeUs: query.sizeUs, stockQuantity: query.inStock === true ? { gt: 0 } : query.inStock === false ? 0 : undefined } } : undefined, AND: query.minPrice != null || query.maxPrice != null ? [{ OR: [{ basePrice: { gte: query.minPrice, lte: query.maxPrice } }, { variants: { some: variantPrice } }] }] : undefined };
    where.publishedAt = { not: null };
    if (query.q) where.OR = [{ title: { contains: query.q, mode: 'insensitive' } }, { slug: { contains: query.q, mode: 'insensitive' } }, { description: { contains: query.q, mode: 'insensitive' } }, { category: { name: { contains: query.q, mode: 'insensitive' } } }, { variants: { some: { sku: { contains: query.q, mode: 'insensitive' } } } }];
    const orderBy: Prisma.ProductOrderByWithRelationInput = query.sort === 'newest' ? { createdAt: 'desc' } : { basePrice: query.sort === 'price_asc' ? 'asc' : 'desc' };
    const [products, total] = await this.prisma.$transaction([this.prisma.product.findMany({ where, include: productInclude, orderBy, skip: (query.page - 1) * query.pageSize, take: query.pageSize }), this.prisma.product.count({ where })]);
    return mapProductList(products, query.page, query.pageSize, total);
  }

  async getBySlug(slug: string): Promise<ProductDetail> { const product = await this.prisma.product.findUnique({ where: { slug }, include: productInclude }); if (!product) throw new NotFoundException('Product not found'); return mapProduct(product); }
  async create(input: CreateProductInput): Promise<ProductDetail> { await this.validateRelations(input.categoryId, input.occasionIds); try { const { categoryId, occasionIds, ...data } = input; const product = await this.prisma.product.create({ data: { ...data, category: categoryId ? { connect: { id: categoryId } } : undefined, occasions: { connect: occasionIds.map((id) => ({ id })) } }, include: productInclude }); return mapProduct(product); } catch (error) { this.handleUnique(error, 'A product with this slug already exists'); throw error; } }
  async update(id: string, input: UpdateProductInput): Promise<ProductDetail> { await this.requireProduct(id); await this.validateRelations(input.categoryId, input.occasionIds); try { const product = await this.prisma.product.update({ where: { id }, data: this.productData(input), include: productInclude }); return mapProduct(product); } catch (error) { this.handleUnique(error, 'A product with this slug already exists'); throw error; } }
  async archive(id: string): Promise<void> { await this.requireProduct(id); await this.prisma.$transaction([this.prisma.product.update({ where: { id }, data: { isActive: false } }), this.prisma.productVariant.updateMany({ where: { productId: id }, data: { isActive: false } })]); }
  async variants(productId: string): Promise<ProductDetail['variants']> { return (await this.getById(productId)).variants; }
  async createVariant(productId: string, input: CreateVariantInput): Promise<ProductDetail['variants'][number]> { await this.requireProduct(productId); await this.requireColor(input.colorId); try { await this.prisma.productVariant.create({ data: { productId, ...input } }); return (await this.getById(productId)).variants.find((variant) => variant.sku === input.sku)!; } catch (error) { this.handleUnique(error, 'SKU or product/color/size combination already exists'); throw error; } }
  async updateVariant(productId: string, variantId: string, input: UpdateVariantInput): Promise<ProductDetail['variants'][number]> { await this.requireProduct(productId); const variant = await this.prisma.productVariant.findFirst({ where: { id: variantId, productId } }); if (!variant) throw new NotFoundException('Variant not found for this product'); if (input.colorId) await this.requireColor(input.colorId); try { await this.prisma.productVariant.update({ where: { id: variantId }, data: input }); return (await this.getById(productId)).variants.find((item) => item.id === variantId)!; } catch (error) { this.handleUnique(error, 'SKU or product/color/size combination already exists'); throw error; } }

  private async getById(id: string): Promise<ProductDetail> { const product = await this.prisma.product.findUnique({ where: { id }, include: productInclude }); if (!product) throw new NotFoundException('Product not found'); return mapProduct(product); }
  private async requireProduct(id: string): Promise<Product> { const product = await this.prisma.product.findUnique({ where: { id } }); if (!product) throw new NotFoundException('Product not found'); return product; }
  private async requireColor(id: string): Promise<void> { if (!await this.prisma.color.findFirst({ where: { id, isActive: true } })) throw new NotFoundException('Invalid color'); }
  private async validateRelations(categoryId?: string | null, occasionIds?: string[]): Promise<void> { if (categoryId && !await this.prisma.category.findFirst({ where: { id: categoryId, isActive: true } })) throw new NotFoundException('Invalid category'); if (occasionIds && await this.prisma.occasion.count({ where: { id: { in: occasionIds }, isActive: true } }) !== new Set(occasionIds).size) throw new NotFoundException('Invalid occasion'); }
  private productData(input: CreateProductInput | UpdateProductInput): Prisma.ProductUpdateInput { const { categoryId, occasionIds, ...data } = input; return { ...data, category: categoryId === null ? { disconnect: true } : categoryId ? { connect: { id: categoryId } } : undefined, occasions: occasionIds ? { set: occasionIds.map((id) => ({ id })) } : undefined }; }
  private handleUnique(error: unknown, message: string): void { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') throw new ConflictException(message); }
}
