import type { Prisma } from '@footwear/database';
import type { ProductDetail, ProductListResponse } from '@footwear/shared';
import { effectivePrice, variantAvailable } from './catalog.rules';

export const productInclude = { category: true, occasions: true, media: { orderBy: { position: 'asc' as const } }, variants: { include: { color: true }, orderBy: [{ color: { name: 'asc' as const } }, { sizeEu: 'asc' as const }] } } satisfies Prisma.ProductInclude;
type ProductRecord = Prisma.ProductGetPayload<{ include: typeof productInclude }>;
const decimal = (value: { toNumber(): number } | null): number | null => value?.toNumber() ?? null;

export function mapProduct(product: ProductRecord): ProductDetail {
  const variants = product.variants.map((variant) => ({ id: variant.id, sku: variant.sku, color: { id: variant.color.id, name: variant.color.name, slug: variant.color.slug, hex: variant.color.hex }, sizeEu: decimal(variant.sizeEu), sizeUk: decimal(variant.sizeUk), sizeUs: decimal(variant.sizeUs), stockQuantity: variant.stockQuantity, isAvailable: variantAvailable(variant.isActive, variant.stockQuantity), priceOverride: decimal(variant.priceOverride), effectivePrice: effectivePrice(product.basePrice.toNumber(), decimal(variant.priceOverride)), weightGrams: variant.weightGrams, isActive: variant.isActive }));
  return { id: product.id, title: product.title, slug: product.slug, description: product.description, basePrice: product.basePrice.toNumber(), effectivePriceFrom: variants.length ? Math.min(...variants.map((variant) => variant.effectivePrice)) : product.basePrice.toNumber(), category: product.category && { id: product.category.id, name: product.category.name, slug: product.category.slug }, gender: product.gender, material: product.material, soleType: product.soleType, heelType: product.heelType, occasions: product.occasions.map(({ id, name, slug }) => ({ id, name, slug })), isActive: product.isActive, isAvailable: variants.some((variant) => variant.isAvailable), createdAt: product.createdAt.toISOString(), variants, media: product.media.map((media) => ({ id: media.id, type: media.type, objectKey: media.objectKey, altText: media.altText, position: media.position, mediaPosition: media.mediaPosition, isPrimary: media.isPrimary, variantId: media.variantId })) };
}
export function mapProductList(products: ProductRecord[], page: number, pageSize: number, total: number): ProductListResponse { return { data: products.map((product) => { const detail = mapProduct(product); return { id: detail.id, title: detail.title, slug: detail.slug, description: detail.description, basePrice: detail.basePrice, effectivePriceFrom: detail.effectivePriceFrom, category: detail.category, gender: detail.gender, material: detail.material, soleType: detail.soleType, heelType: detail.heelType, occasions: detail.occasions, isActive: detail.isActive, isAvailable: detail.isAvailable, createdAt: detail.createdAt }; }), pagination: { page, pageSize, total, totalPages: Math.ceil(total / pageSize) } }; }
