import { Body, Controller, Delete, Get, HttpCode, Param, Patch, Post, Query, UseGuards } from '@nestjs/common';
import { ApiBadRequestResponse, ApiConflictResponse, ApiCreatedResponse, ApiNoContentResponse, ApiNotFoundResponse, ApiOkResponse, ApiOperation, ApiParam, ApiQuery, ApiTags } from '@nestjs/swagger';
import { bulkProductFamiliesSchema,bulkProductVisibilitySchema,createProductFamilySchema,productColorwayInputSchema,createProductSchema, createVariantSchema, productQuerySchema,updateProductFamilySchema, updateProductSchema, updateVariantSchema,type BulkProductFamiliesInput,type BulkProductVisibilityInput, type CreateProductFamilyInput,type ProductColorwayInput,type CreateProductInput, type CreateVariantInput, type ProductQuery,type UpdateProductFamilyInput, type UpdateProductInput, type UpdateVariantInput } from '@footwear/shared';
import { ZodValidationPipe } from '../common/zod-validation.pipe';
import { AuthGuard } from '../auth/auth.guard';
import { AdminGuard } from '../auth/admin.guard';
import { ProductsService } from './products.service';
import { CurrentUser } from '../auth/current-user.decorator';
import type { AuthenticatedUser } from '../auth/auth.types';
import { Roles } from '../auth/roles.decorator';
import { RolesGuard } from '../auth/roles.guard';

@ApiTags('products')
@Controller('products')
export class ProductsController {
  constructor(private readonly products: ProductsService) {}
  @Get() @ApiOperation({ summary: 'List active catalog products' }) @ApiQuery({ name: 'sort', required: false, enum: ['newest', 'price_asc', 'price_desc', 'bestsellers', 'rating'] }) @ApiQuery({ name: 'page', required: false, type: Number }) @ApiQuery({ name: 'pageSize', required: false, type: Number }) @ApiQuery({ name: 'brand', required: false }) @ApiQuery({ name: 'gender', required: false, enum: ['WOMEN', 'MEN', 'UNISEX', 'KIDS'] }) @ApiQuery({ name: 'color', required: false }) @ApiQuery({ name: 'sizeEu', required: false, type: Number }) @ApiQuery({ name: 'sizeUk', required: false, type: Number }) @ApiQuery({ name: 'sizeUs', required: false, type: Number }) @ApiQuery({ name: 'material', required: false }) @ApiQuery({ name: 'soleType', required: false }) @ApiQuery({ name: 'minPrice', required: false, type: Number }) @ApiQuery({ name: 'maxPrice', required: false, type: Number }) @ApiQuery({ name: 'inStock', required: false, type: Boolean }) @ApiOkResponse({ description: 'Paginated catalog results' }) @ApiBadRequestResponse({ description: 'Invalid query' })
  list(@Query(new ZodValidationPipe(productQuerySchema)) query: ProductQuery) { return this.products.list(query); }
  @Get('slug/:slug') @ApiOperation({ summary: 'Get storefront product detail by slug' }) @ApiParam({ name: 'slug' }) @ApiOkResponse({ description: 'Product detail with variants and effective prices' }) @ApiNotFoundResponse({ description: 'Product not found' }) getBySlug(@Param('slug') slug: string) { return this.products.getBySlug(slug); }
  @Get(':id/related') related(@Param('id')id:string){return this.products.related(id)}
  @Post('families') @UseGuards(AuthGuard,AdminGuard) createFamily(@CurrentUser() actor:AuthenticatedUser,@Body(new ZodValidationPipe(createProductFamilySchema))input:CreateProductFamilyInput){return this.products.createFamily(actor,input)}
  @Post('families/:familyId/colorways') @UseGuards(AuthGuard,AdminGuard) addColorway(@CurrentUser()actor:AuthenticatedUser,@Param('familyId')familyId:string,@Body(new ZodValidationPipe(productColorwayInputSchema))input:ProductColorwayInput){return this.products.addColorway(actor,familyId,input)}
  @Patch('families/:familyId') @UseGuards(AuthGuard,AdminGuard) updateFamily(@CurrentUser()actor:AuthenticatedUser,@Param('familyId')familyId:string,@Body(new ZodValidationPipe(updateProductFamilySchema))input:UpdateProductFamilyInput){return this.products.updateFamily(actor,familyId,input)}
  @Delete('families/bulk/permanent') @Roles('SUPER_ADMIN') @UseGuards(AuthGuard,AdminGuard,RolesGuard) deleteFamilies(@CurrentUser()actor:AuthenticatedUser,@Body(new ZodValidationPipe(bulkProductFamiliesSchema))input:BulkProductFamiliesInput){return this.products.deleteFamilies(actor,input.productFamilyIds)}
  @Patch('families/bulk/visibility') @UseGuards(AuthGuard,AdminGuard) visibility(@CurrentUser()actor:AuthenticatedUser,@Body(new ZodValidationPipe(bulkProductVisibilitySchema))input:BulkProductVisibilityInput){return this.products.setFamiliesVisibility(actor,input.productFamilyIds,input.visible)}
  @Delete('families/:familyId/permanent') @Roles('SUPER_ADMIN') @UseGuards(AuthGuard,AdminGuard,RolesGuard) deleteFamily(@CurrentUser()actor:AuthenticatedUser,@Param('familyId')familyId:string){return this.products.deleteFamily(actor,familyId)}
  @Post() @UseGuards(AuthGuard,AdminGuard) @ApiCreatedResponse({ description: 'Product created' }) @ApiConflictResponse({ description: 'Slug already exists' }) create(@CurrentUser() actor:AuthenticatedUser,@Body(new ZodValidationPipe(createProductSchema)) input: CreateProductInput) { return this.products.create(actor,input); }
  @Patch(':id') @UseGuards(AuthGuard,AdminGuard) @ApiOkResponse({ description: 'Product updated' }) @ApiNotFoundResponse({ description: 'Product not found or invalid relation' }) update(@CurrentUser() actor:AuthenticatedUser,@Param('id') id: string, @Body(new ZodValidationPipe(updateProductSchema)) input: UpdateProductInput) { return this.products.update(actor,id, input); }
  @Delete(':id') @UseGuards(AuthGuard,AdminGuard) @HttpCode(204) @ApiNoContentResponse({ description: 'Product and variants archived; no commerce data is deleted' }) async archive(@CurrentUser() actor:AuthenticatedUser,@Param('id') id: string) { await this.products.archive(actor,id); }
  @Delete(':id/permanent') @Roles('SUPER_ADMIN') @UseGuards(AuthGuard,AdminGuard,RolesGuard) deleteColorway(@CurrentUser()actor:AuthenticatedUser,@Param('id')id:string){return this.products.deleteColorway(actor,id)}
  @Get(':productId/variants') @UseGuards(AuthGuard,AdminGuard) @ApiOkResponse({ description: 'All variants, including inactive and out-of-stock variants' }) variants(@Param('productId') productId: string) { return this.products.variants(productId); }
  @Post(':productId/variants') @UseGuards(AuthGuard,AdminGuard) @ApiCreatedResponse({ description: 'Variant created' }) @ApiConflictResponse({ description: 'Duplicate SKU or variant combination' }) createVariant(@CurrentUser() actor:AuthenticatedUser,@Param('productId') productId: string, @Body(new ZodValidationPipe(createVariantSchema)) input: CreateVariantInput) { return this.products.createVariant(actor,productId, input); }
  @Patch(':productId/variants/:variantId') @UseGuards(AuthGuard,AdminGuard) @ApiOkResponse({ description: 'Variant updated' }) @ApiNotFoundResponse({ description: 'Product/variant mismatch or missing variant' }) updateVariant(@CurrentUser() actor:AuthenticatedUser,@Param('productId') productId: string, @Param('variantId') variantId: string, @Body(new ZodValidationPipe(updateVariantSchema)) input: UpdateVariantInput) { return this.products.updateVariant(actor,productId, variantId, input); }
  @Delete(':productId/variants/:variantId') @Roles('SUPER_ADMIN') @UseGuards(AuthGuard,AdminGuard,RolesGuard) @HttpCode(204) removeVariant(@CurrentUser()actor:AuthenticatedUser,@Param('productId')productId:string,@Param('variantId')variantId:string){return this.products.removeVariant(actor,productId,variantId)}
}
