import { ConflictException, Injectable, NotFoundException,ServiceUnavailableException } from '@nestjs/common';
import { Prisma, type Product } from '@footwear/database';
import type { AuthenticatedUser } from '../auth/auth.types';
import type { CreateProductFamilyInput,CreateProductInput,CreateVariantInput,ProductColorwayInput,ProductDetail,ProductListResponse,ProductQuery,UpdateProductFamilyInput,UpdateProductInput,UpdateVariantInput } from '@footwear/shared';
import { AuditService } from '../audit/audit.service';
import { PrismaService } from '../infrastructure/prisma/prisma.service';
import { ObjectStorageService } from '../media/object-storage.service';
import { mapProduct,mapProductList,productInclude } from './products.mapper';
import { selectRelated } from './related-products';
import { createFamilySlug, createProductSlug, createUniqueSlug } from './product-slug';
import { compareCatalogPrice } from './catalog.rules';
import { BadRequestException } from '@nestjs/common';

@Injectable()
export class ProductsService {
  constructor(private readonly prisma:PrismaService,private readonly audit:AuditService,private readonly storage:ObjectStorageService){}
  async list(query:ProductQuery):Promise<ProductListResponse>{
    if(query.sort==='bestsellers'||query.sort==='rating')throw new ConflictException(`Sort '${query.sort}' is not available until its domain is implemented`);
    const variantPrice:Prisma.ProductVariantWhereInput={isActive:true};
    const where:Prisma.ProductWhereInput={isActive:true,isNewArrival:query.newArrival,publishedAt:{not:null},brand:query.brand?{slug:query.brand,isActive:true}:undefined,gender:query.gender,material:query.material?{equals:query.material,mode:'insensitive'}:undefined,soleType:query.soleType?{equals:query.soleType,mode:'insensitive'}:undefined,color:query.color?{slug:query.color,isActive:true}:undefined,variants:query.sizeEu||query.sizeUk||query.sizeUs||query.inStock!=null?{some:{...variantPrice,sizeEu:query.sizeEu,sizeUk:query.sizeUk,sizeUs:query.sizeUs,stockQuantity:query.inStock===true?{gt:0}:query.inStock===false?0:undefined}}:undefined};
    if(query.q)where.OR=[{title:{contains:query.q,mode:'insensitive'}},{family:{name:{contains:query.q,mode:'insensitive'}}},{color:{name:{contains:query.q,mode:'insensitive'}}},{slug:{contains:query.q,mode:'insensitive'}},{description:{contains:query.q,mode:'insensitive'}},{brand:{name:{contains:query.q,mode:'insensitive'}}},{variants:{some:{sku:{contains:query.q,mode:'insensitive'}}}}];
    const usesEffectivePrice=query.sort==='price_asc'||query.sort==='price_desc'||query.minPrice!=null||query.maxPrice!=null;
    if(usesEffectivePrice){const products=await this.prisma.product.findMany({where,include:productInclude,orderBy:{createdAt:'desc'}});const filtered=products.map(product=>({product,price:mapProduct(product).effectivePriceFrom,createdAt:product.createdAt,id:product.id})).filter(({price})=>(query.minPrice==null||price>=query.minPrice)&&(query.maxPrice==null||price<=query.maxPrice));if(query.sort==='price_asc'||query.sort==='price_desc')filtered.sort((a,b)=>compareCatalogPrice(a,b,query.sort==='price_asc'?'asc':'desc'));const total=filtered.length,start=(query.page-1)*query.pageSize;return mapProductList(filtered.slice(start,start+query.pageSize).map(row=>row.product),query.page,query.pageSize,total)}
    const[products,total]=await this.prisma.$transaction([this.prisma.product.findMany({where,include:productInclude,orderBy:{createdAt:'desc'},skip:(query.page-1)*query.pageSize,take:query.pageSize}),this.prisma.product.count({where})]);return mapProductList(products,query.page,query.pageSize,total);
  }
  async getBySlug(slug:string):Promise<ProductDetail>{const product=await this.prisma.product.findFirst({where:{slug,isActive:true,publishedAt:{not:null}},include:productInclude});if(!product)throw new NotFoundException('Product not found');return mapProduct(product)}
  async related(id:string){const current=await this.prisma.product.findFirst({where:{id,isActive:true,publishedAt:{not:null}},include:productInclude});if(!current)throw new NotFoundException('Product not found');const candidates=await this.prisma.product.findMany({where:{familyId:{not:current.familyId},isActive:true,publishedAt:{not:null}},include:productInclude,orderBy:[{createdAt:'desc'},{id:'asc'}],take:100});return selectRelated(current,candidates).map(candidate=>{const detail=mapProduct(candidate),{siblings,variants,media,...summary}=detail;void siblings;void variants;void media;return summary})}
  async createFamily(actor:AuthenticatedUser,input:CreateProductFamilyInput){await this.validateBrand(input.brandId);try{return await this.prisma.$transaction(async tx=>{const familySlug=await createUniqueSlug(createFamilySlug(input.name),async slug=>Boolean(await tx.productFamily.findUnique({where:{slug},select:{id:true}})));const family=await tx.productFamily.create({data:{name:input.name,slug:familySlug}});await this.audit.write(actor,'PRODUCT_FAMILY_CREATED','ProductFamily',family.id,{name:family.name},tx);const products=[];for(const colorway of input.colorways){const color=await tx.color.findFirst({where:{id:colorway.colorId,isActive:true}});if(!color)throw new NotFoundException('Invalid color');const slug=await createUniqueSlug(createProductSlug(family.name,color.name),async candidate=>Boolean(await tx.product.findUnique({where:{slug:candidate},select:{id:true}})));const product=await tx.product.create({data:{title:this.generatedName(family.name,color.name),slug,familyId:family.id,colorId:color.id,description:input.description,basePrice:colorway.basePrice,salePrice:colorway.salePrice??null,brandId:input.brandId,gender:input.gender,material:input.material,soleType:input.soleType,heelType:input.heelType,isActive:colorway.isActive,publishedAt:colorway.publishedAt,variants:{create:colorway.variants.map(v=>({...v,colorId:color.id}))}}});await this.audit.write(actor,'PRODUCT_CREATED','Product',product.id,{familyId:family.id,colorId:color.id,variantCount:colorway.variants.length},tx);products.push(product)}return{family,products}},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable,maxWait:5000,timeout:20000})}catch(error){this.handleUnique(error,'This model, colorway, or SKU already exists');throw error}}
  async addColorway(actor:AuthenticatedUser,familyId:string,input:ProductColorwayInput){const source=await this.prisma.product.findFirst({where:{familyId},include:{family:true}});if(!source)throw new NotFoundException('Product family not found');const color=await this.prisma.color.findFirst({where:{id:input.colorId,isActive:true}});if(!color)throw new NotFoundException('Invalid color');try{return await this.prisma.$transaction(async tx=>{const slug=await createUniqueSlug(createProductSlug(source.family.name,color.name),async candidate=>Boolean(await tx.product.findUnique({where:{slug:candidate},select:{id:true}})));const product=await tx.product.create({data:{familyId,colorId:color.id,title:this.generatedName(source.family.name,color.name),slug,description:source.description,basePrice:input.basePrice,salePrice:input.salePrice??null,brandId:source.brandId,gender:source.gender,material:source.material,soleType:source.soleType,heelType:source.heelType,isActive:input.isActive,publishedAt:input.publishedAt,variants:{create:input.variants.map(v=>({...v,colorId:color.id}))}}});await this.audit.write(actor,'PRODUCT_CREATED','Product',product.id,{familyId,colorId:color.id},tx);return product})}catch(error){this.handleUnique(error,'This model already has that colorway, or the SKU is already in use');throw error}}
  async updateFamily(actor:AuthenticatedUser,familyId:string,input:UpdateProductFamilyInput){const current=await this.prisma.productFamily.findUnique({where:{id:familyId}});if(!current)throw new NotFoundException('Product family not found');try{return await this.prisma.$transaction(async tx=>{const name=input.name??current.name;const slug=await createUniqueSlug(createFamilySlug(name),async candidate=>Boolean(await tx.productFamily.findFirst({where:{slug:candidate,id:{not:familyId}},select:{id:true}})));const family=await tx.productFamily.update({where:{id:familyId},data:{name,slug}});const products=await tx.product.findMany({where:{familyId},select:{id:true,color:{select:{name:true}}}});for(const product of products){const productSlug=await createUniqueSlug(createProductSlug(family.name,product.color.name),async candidate=>Boolean(await tx.product.findFirst({where:{slug:candidate,id:{not:product.id}},select:{id:true}})));await tx.product.update({where:{id:product.id},data:{title:this.generatedName(family.name,product.color.name),slug:productSlug}})}await this.audit.write(actor,'PRODUCT_FAMILY_UPDATED','ProductFamily',familyId,input,tx);return family})}catch(error){this.handleUnique(error,'Unable to generate a unique model URL');throw error}}
  async deleteFamily(actor:AuthenticatedUser,familyId:string){const family=await this.prisma.productFamily.findUnique({where:{id:familyId},include:{products:{select:{id:true,media:{select:{objectKey:true}}}}}});if(!family)throw new NotFoundException('Product family not found');await this.ensureNoActiveOrders(family.products.map(product=>product.id));await this.removeObjects(family.products.flatMap(product=>product.media.map(media=>media.objectKey)));await this.prisma.$transaction(async tx=>{await tx.product.deleteMany({where:{familyId}});await tx.productFamily.delete({where:{id:familyId}});await this.audit.write(actor,'PRODUCT_DELETED','ProductFamily',familyId,{name:family.name},tx)});return{deleted:true,familyId}}
  async deleteFamilies(actor:AuthenticatedUser,familyIds:string[]){const families=await this.prisma.productFamily.findMany({where:{id:{in:familyIds}},include:{products:{select:{id:true,media:{select:{objectKey:true}}}}}});if(families.length!==familyIds.length)throw new NotFoundException('One or more product families no longer exist');await this.ensureNoActiveOrders(families.flatMap(family=>family.products.map(product=>product.id)));await this.removeObjects(families.flatMap(family=>family.products.flatMap(product=>product.media.map(media=>media.objectKey))));await this.prisma.$transaction(async tx=>{await tx.product.deleteMany({where:{familyId:{in:familyIds}}});await tx.productFamily.deleteMany({where:{id:{in:familyIds}}});await this.audit.write(actor,'PRODUCT_BULK_DELETED','ProductFamily',null,{count:families.length,familyIds},tx)});return{deleted:families.length}}
  async setFamiliesVisibility(actor:AuthenticatedUser,familyIds:string[],visible:boolean){if(await this.prisma.productFamily.count({where:{id:{in:familyIds}}})!==familyIds.length)throw new NotFoundException('One or more product families no longer exist');return this.prisma.$transaction(async tx=>{const result=await tx.product.updateMany({where:{familyId:{in:familyIds}},data:{isActive:visible}});if(visible)await tx.product.updateMany({where:{familyId:{in:familyIds},publishedAt:null},data:{publishedAt:new Date()}});await this.audit.write(actor,visible?'PRODUCTS_SHOWN':'PRODUCTS_HIDDEN','ProductFamily',null,{count:familyIds.length,familyIds},tx);return{updatedFamilies:familyIds.length,updatedColorways:result.count,visible}})}
  async deleteColorway(actor:AuthenticatedUser,id:string){const product=await this.prisma.product.findUnique({where:{id},include:{family:{select:{id:true,name:true,_count:{select:{products:true}}}},color:{select:{name:true}},media:{select:{objectKey:true}}}});if(!product)throw new NotFoundException('Product colorway not found');await this.ensureNoActiveOrders([id]);if(product.family._count.products===1)return this.deleteFamily(actor,product.family.id);await this.removeObjects(product.media.map(media=>media.objectKey));await this.prisma.$transaction(async tx=>{await tx.product.delete({where:{id}});await this.audit.write(actor,'COLORWAY_DELETED','Product',id,{name:`${product.family.name} | ${product.color.name}`},tx)});return{deleted:true,productId:id,familyDeleted:false}}
  async create(actor:AuthenticatedUser,input:CreateProductInput):Promise<ProductDetail>{await this.validateBrand(input.brandId);const identity=await this.identity(input.familyId,input.colorId);try{const{brandId,familyId,colorId,...data}=input;const slug=await createUniqueSlug(createProductSlug(identity.family.name,identity.color.name),async candidate=>Boolean(await this.prisma.product.findUnique({where:{slug:candidate},select:{id:true}})));const product=await this.prisma.product.create({data:{...data,slug,title:this.generatedName(identity.family.name,identity.color.name),family:{connect:{id:familyId}},color:{connect:{id:colorId}},brand:brandId?{connect:{id:brandId}}:undefined},include:productInclude});await this.audit.write(actor,'PRODUCT_CREATED','Product',product.id,{familyId:input.familyId,colorId:input.colorId});return mapProduct(product)}catch(error){this.handleUnique(error,'This model already has that colorway');throw error}}
  async update(actor:AuthenticatedUser,id:string,input:UpdateProductInput):Promise<ProductDetail>{const current=await this.requireProduct(id);const finalBase=input.basePrice??current.basePrice.toNumber(),finalSale=input.salePrice===undefined?current.salePrice?.toNumber()??null:input.salePrice;if(finalBase<=0||finalSale!=null&&(finalSale<=0||finalSale>=finalBase))throw new BadRequestException('Sale price must be positive and lower than the regular price');await this.validateBrand(input.brandId);const familyId=input.familyId??current.familyId,colorId=input.colorId??current.colorId,identity=await this.identity(familyId,colorId);try{const slug=await createUniqueSlug(createProductSlug(identity.family.name,identity.color.name),async candidate=>Boolean(await this.prisma.product.findFirst({where:{slug:candidate,id:{not:id}},select:{id:true}})));const product=await this.prisma.product.update({where:{id},data:{...this.productData(input),slug,title:this.generatedName(identity.family.name,identity.color.name)},include:productInclude});await this.audit.write(actor,'PRODUCT_UPDATED','Product',id);if(input.publishedAt||input.isActive===true)await this.audit.write(actor,'PRODUCT_PUBLISHED','Product',id);return mapProduct(product)}catch(error){this.handleUnique(error,'This model already has that colorway');throw error}}
  async archive(actor:AuthenticatedUser,id:string):Promise<void>{await this.requireProduct(id);await this.prisma.$transaction(async tx=>{await tx.product.update({where:{id},data:{isActive:false}});await tx.productVariant.updateMany({where:{productId:id},data:{isActive:false}});await this.audit.write(actor,'PRODUCT_ARCHIVED','Product',id,undefined,tx)})}
  async variants(productId:string){return(await this.getById(productId)).variants}
  async createVariant(actor:AuthenticatedUser,productId:string,input:CreateVariantInput){const product=await this.requireProduct(productId);if(input.colorId!==product.colorId)throw new ConflictException('Variant color must match its product colorway');try{const row=await this.prisma.productVariant.create({data:{productId,...input}});await this.audit.write(actor,'VARIANT_CREATED','ProductVariant',row.id,{productId,sku:row.sku});return(await this.getById(productId)).variants.find(v=>v.id===row.id)!}catch(error){this.handleUnique(error,'This size or SKU already exists for this colorway');throw error}}
  async updateVariant(actor:AuthenticatedUser,productId:string,variantId:string,input:UpdateVariantInput){const product=await this.requireProduct(productId);const variant=await this.prisma.productVariant.findFirst({where:{id:variantId,productId}});if(!variant)throw new NotFoundException('Variant not found for this product');if(input.colorId&&input.colorId!==product.colorId)throw new ConflictException('Variant color must match its product colorway');try{await this.prisma.productVariant.update({where:{id:variantId},data:input});await this.audit.write(actor,'VARIANT_UPDATED','ProductVariant',variantId,{productId});return(await this.getById(productId)).variants.find(v=>v.id===variantId)!}catch(error){this.handleUnique(error,'This size or SKU already exists for this colorway');throw error}}
  async removeVariant(actor:AuthenticatedUser,productId:string,variantId:string){const variant=await this.prisma.productVariant.findFirst({where:{id:variantId,productId}});if(!variant)throw new NotFoundException('Variant not found for this product');if(await this.prisma.orderItem.count({where:{variantId,order:{status:{in:['PENDING','CONFIRMED','PROCESSING','SHIPPED']}}}}))throw new ConflictException('This variant cannot be permanently purged while an active order depends on it');await this.prisma.$transaction(async tx=>{await tx.productVariant.delete({where:{id:variantId}});await this.audit.write(actor,'VARIANT_UPDATED','ProductVariant',variantId,{productId,deleted:true},tx)})}
  private async getById(id:string){const product=await this.prisma.product.findUnique({where:{id},include:productInclude});if(!product)throw new NotFoundException('Product not found');return mapProduct(product)}
  private async requireProduct(id:string):Promise<Product>{const product=await this.prisma.product.findUnique({where:{id}});if(!product)throw new NotFoundException('Product not found');return product}
  private async identity(familyId:string,colorId:string){const[family,color]=await Promise.all([this.prisma.productFamily.findUnique({where:{id:familyId}}),this.prisma.color.findFirst({where:{id:colorId,isActive:true}})]);if(!family)throw new NotFoundException('Invalid product family');if(!color)throw new NotFoundException('Invalid color');return{family,color}}
  private generatedName(family:string,color:string){return`${family.trim()} | ${color.trim()}`}
  private async validateBrand(brandId?:string|null){if(brandId&&!await this.prisma.brand.findFirst({where:{id:brandId,isActive:true}}))throw new NotFoundException('Invalid brand')}
  private productData(input:UpdateProductInput):Prisma.ProductUpdateInput{const{brandId,familyId,colorId,...data}=input;return{...data,family:familyId?{connect:{id:familyId}}:undefined,color:colorId?{connect:{id:colorId}}:undefined,brand:brandId===null?{disconnect:true}:brandId?{connect:{id:brandId}}:undefined}}
  private handleUnique(error:unknown,message:string){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002')throw new ConflictException(message)}
  private async ensureNoActiveOrders(productIds:string[]){if(!(this.prisma as unknown as {productVariant?:unknown;orderItem?:unknown}).productVariant||!(this.prisma as unknown as {orderItem?:unknown}).orderItem)return;const variants=await this.prisma.productVariant.findMany({where:{productId:{in:productIds}},select:{id:true}});if(await this.prisma.orderItem.count({where:{variantId:{in:variants.map(variant=>variant.id)},order:{status:{in:['PENDING','CONFIRMED','PROCESSING','SHIPPED']}}}}))throw new ConflictException('This catalog item cannot be permanently purged while an active order depends on it')}
  private async removeObjects(keys:string[]){const results=await Promise.allSettled(keys.map(key=>this.storage.remove(key)));const failed=results.filter(result=>result.status==='rejected');if(failed.length)throw new ServiceUnavailableException(`Permanent deletion stopped because ${failed.length} media object${failed.length===1?'':'s'} could not be removed. Database records were retained; retry the deletion.`)}
}
