import { headers } from 'next/headers';
import Link from 'next/link';
import { redirect } from 'next/navigation';
import { isInvoiceAvailable } from '@footwear/shared';
import { formatBDT } from '@/components/catalog/product-card';
import { DownloadInvoiceButton } from '@/components/orders/download-invoice-button';
import { auth } from '@/lib/auth';
import { ordersApi } from '@/lib/api-client';

export default async function OrderDetailPage({ params }: { params: Promise<{ orderNumber: string }> }) {
  const incoming = await headers();
  if (!await auth.api.getSession({ headers: incoming })) redirect('/login?returnTo=/account/orders');
  const { orderNumber } = await params;
  const order = await ordersApi.get(orderNumber, { headers: { cookie: incoming.get('cookie') ?? '' } });
  return <article className="container page"><Link className="text-sm underline" href="/account/orders">← Back to orders</Link><div className="mt-7 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Order details</p><h1 className="title mt-3">{order.orderNumber}</h1><p className="mt-3 text-sm muted">Placed {new Date(order.createdAt).toLocaleString('en-BD')}</p>{isInvoiceAvailable(order) && <div className="mt-4"><DownloadInvoiceButton orderNumber={order.orderNumber} /></div>}</div><div className="flex gap-2"><span className="status">{order.status}</span><span className={`status ${order.paymentStatus === 'PAID' ? 'success' : ''}`}>{order.paymentStatus}</span></div></div><div className="mt-10 grid items-start gap-8 lg:grid-cols-[1fr_22rem]"><section><h2 className="section-title">Items</h2><ul className="mt-5 divide-y divide-[var(--line)] border-y border-[var(--line)]">{order.items.map((item) => <li className="flex justify-between gap-5 py-5" key={item.id}><div><Link className="font-semibold hover:underline" href={`/product/${item.productSlug}`}>{item.productName}</Link><p className="mt-1 text-sm muted">{item.colorName} · {item.sizeEu ? `EU ${item.sizeEu}` : item.sizeUk ? `UK ${item.sizeUk}` : `US ${item.sizeUs}`} · Qty {item.quantity}</p><p className="mt-1 text-xs muted">{formatBDT(item.unitPrice)} each</p></div><strong>{formatBDT(item.lineSubtotal)}</strong></li>)}</ul><div className="mt-8 grid gap-8 sm:grid-cols-2"><div><h2 className="font-semibold">Shipping address</h2><address className="mt-3 text-sm not-italic leading-6 muted">{order.shippingAddress.recipientName}<br />{order.shippingAddress.addressLine}{order.shippingAddress.area ? `, ${order.shippingAddress.area}` : ''}<br />{order.shippingAddress.cityDistrict}{order.shippingAddress.postalCode ? ` ${order.shippingAddress.postalCode}` : ''}, {order.shippingAddress.country}<br />{order.shippingAddress.phone}</address></div><div><h2 className="font-semibold">Payment</h2><p className="mt-3 text-sm muted">Cash on Delivery<br />{order.paymentStatus}</p></div></div></section><aside className="panel"><h2 className="section-title">Summary</h2><dl className="mt-6 space-y-3 text-sm"><div className="flex justify-between"><dt>Subtotal</dt><dd>{formatBDT(order.subtotal)}</dd></div><div className="flex justify-between"><dt>{order.shippingMethod.name}</dt><dd>{formatBDT(order.shippingAmount)}</dd></div><div className="flex justify-between border-t border-[var(--line)] pt-4 text-base font-semibold"><dt>Total</dt><dd>{formatBDT(order.total)}</dd></div></dl></aside></div></article>;
}
