import type { AnnouncementAdmin,OrderDetail,OrderSummary,UpdateAnnouncementInput } from '@footwear/shared';
import { publicEnvironment } from './env';
import type { CreatedFamily } from './product-create-workflow';
export type AdminOrderListItem={orderNumber:string;status:OrderSummary['status'];total:number;createdAt:string;confirmedAt:string|null;contactName:string;contactEmail:string;contactPhone:string;shippingRecipient:string;shippingPhone:string;shippingCityDistrict:string};
export type AdminOrderListResponse={data:AdminOrderListItem[];statusCounts:Record<OrderSummary['status'],number>;pagination:{page:number;pageSize:number;total:number;totalPages:number}};
type AdminFamilyProduct={id:string;title:string;slug:string;basePrice:string|number;salePrice?:string|number|null;isActive:boolean;isNewArrival?:boolean;publishedAt:string|null;color:{id:string;name:string;hex:string|null};variants:Array<{id:string;stockQuantity:number}>;media:Array<{objectKey:string}>};
export type Taxonomy={id:string;name:string;slug:string;isActive:boolean;parentId?:string|null;hex?:string|null};
export type AdminProduct={id:string;title:string;slug:string;description:string;basePrice:string|number;salePrice?:string|number|null;family:{id:string;name:string;slug:string;products?:AdminFamilyProduct[]};color:{id:string;name:string;slug:string;hex:string|null};brand:{id:string;name:string}|null;gender:string|null;material:string|undefined;soleType:string|undefined;heelType:string|undefined;isActive:boolean;isNewArrival?:boolean;publishedAt:string|null;variants:Array<{id:string;sku:string;stockQuantity:number;isActive:boolean;color:{id:string;name:string;hex:string|null};sizeEu:string|number|null;sizeUk:string|number|null;sizeUs:string|number|null;priceOverride:string|number|null}>;media:Array<{id:string;objectKey:string;url:string;position:number;isPrimary:boolean}>};
const storefrontMutation=(path:string,method:string)=>method!=='GET'&&(path.startsWith('/products')||path.startsWith('/admin/catalog/brands')||path.startsWith('/admin/catalog/colors')||path.startsWith('/admin/catalog/variants')||path.startsWith('/admin/products')||path.startsWith('/admin/media'));
async function invalidateStorefront(){try{const response=await fetch('/api/storefront-cache',{method:'POST',credentials:'include',keepalive:true});if(!response.ok)console.error(`Storefront cache invalidation failed (${response.status}).`)}catch(error){console.error('Storefront cache invalidation failed.',error)}}
async function request<T>(path:string,init?:RequestInit):Promise<T>{const method=init?.method?.toUpperCase()??'GET',response=await fetch(`${publicEnvironment.NEXT_PUBLIC_API_URL}${path}`,{...init,credentials:'include',cache:'no-store',headers:{...(!(init?.body instanceof FormData)?{'Content-Type':'application/json'}:{}),...init?.headers}});if(!response.ok){const body=await response.json().catch(()=>null)as{message?:string;detail?:string|{message?:string}}|null;const detail=typeof body?.detail==='string'?body.detail:body?.detail?.message;throw new Error(response.status===404&&detail==='Invalid brand'?'This brand is no longer available. Please select another brand.':body?.message??detail??(response.status===409?'This value is already in use.':`Request failed (${response.status})`))}const result=response.status===204?undefined as T:await response.json()as T;if(storefrontMutation(path,method))void invalidateStorefront();return result}
export const adminApi={
 products:(init?:RequestInit)=>request<[AdminProduct[],number]>('/admin/catalog/products',init),product:(id:string,init?:RequestInit)=>request<AdminProduct>(`/admin/catalog/products/${id}`,init),
 createFamily:(body:unknown)=>request<CreatedFamily>('/products/families',{method:'POST',body:JSON.stringify(body)}),updateFamily:(id:string,body:unknown)=>request(`/products/families/${id}`,{method:'PATCH',body:JSON.stringify(body)}),addColorway:(familyId:string,body:unknown)=>request<{id:string;slug:string}>(`/products/families/${familyId}/colorways`,{method:'POST',body:JSON.stringify(body)}),
 deleteFamily:(id:string)=>request(`/products/families/${id}/permanent`,{method:'DELETE'}),deleteColorway:(id:string)=>request<{familyDeleted?:boolean}>(`/products/${id}/permanent`,{method:'DELETE'}),
 bulkDeleteFamilies:(productFamilyIds:string[])=>request<{deleted:number}>('/products/families/bulk/permanent',{method:'DELETE',body:JSON.stringify({productFamilyIds})}),bulkVisibility:(productFamilyIds:string[],visible:boolean)=>request('/products/families/bulk/visibility',{method:'PATCH',body:JSON.stringify({productFamilyIds,visible})}),
 updateProduct:(id:string,body:unknown)=>request<AdminProduct>(`/products/${id}`,{method:'PATCH',body:JSON.stringify(body)}),createVariant:(productId:string,body:unknown)=>request(`/products/${productId}/variants`,{method:'POST',body:JSON.stringify(body)}),updateVariant:(productId:string,id:string,body:unknown)=>request(`/products/${productId}/variants/${id}`,{method:'PATCH',body:JSON.stringify(body)}),deleteVariant:(productId:string,id:string)=>request<void>(`/products/${productId}/variants/${id}`,{method:'DELETE'}),
 brands:(init?:RequestInit)=>request<Taxonomy[]>('/admin/catalog/brands',init),updateBrand:(id:string,body:unknown)=>request<Taxonomy>(`/admin/catalog/brands/${id}`,{method:'PATCH',body:JSON.stringify(body)}),deleteBrand:(id:string)=>request<{deleted:true;id:string}>(`/admin/catalog/brands/${id}`,{method:'DELETE'}),colors:(init?:RequestInit)=>request<Taxonomy[]>('/admin/catalog/colors',init),createProduct:(body:unknown)=>request<AdminProduct>('/products',{method:'POST',body:JSON.stringify(body)}),updateInventory:(id:string,stockQuantity:number)=>request(`/admin/catalog/variants/${id}/inventory`,{method:'PATCH',body:JSON.stringify({stockQuantity})}),taxonomy:(kind:'brands'|'colors',body:unknown)=>request<Taxonomy>(`/admin/catalog/${kind}`,{method:'POST',body:JSON.stringify(body)}),
 upload:(productId:string,file:File,position?:number)=>{const body=new FormData();body.append('file',file);if(position!==undefined)body.append('position',String(position));return request<{id:string;productId:string;objectKey:string;url:string;position:number}>(`/admin/products/${productId}/media`,{method:'POST',body})},reorderMedia:(productId:string,items:Array<{id:string;position:number}>)=>request<{updated:number}>(`/admin/products/${productId}/media/reorder`,{method:'PATCH',body:JSON.stringify({items})}),deleteMedia:(id:string)=>request(`/admin/media/${id}`,{method:'DELETE'}),
 orders:(params:Record<string,string|number|undefined>={},init?:RequestInit)=>{const query=new URLSearchParams(Object.entries(params).filter((entry):entry is [string,string|number]=>entry[1]!==undefined&&entry[1]!=='').map(([key,value])=>[key,String(value)]));return request<AdminOrderListResponse>(`/admin/orders${query.size?`?${query}`:''}`,init)},order:(number:string,init?:RequestInit)=>request<OrderDetail>(`/admin/orders/${number}`,init),status:(number:string,status:string)=>request<OrderDetail>(`/admin/orders/${number}/status`,{method:'PATCH',body:JSON.stringify({status})})
};
export const announcementAdminApi={get:(init?:RequestInit)=>request<AnnouncementAdmin>('/admin/announcement',init),update:(body:UpdateAnnouncementInput)=>request<AnnouncementAdmin>('/admin/announcement',{method:'PATCH',body:JSON.stringify(body)})};
