import { afterEach, describe, expect, it, vi } from 'vitest';
import { api, ApiError, cartApi, checkoutApi, ordersApi } from './api-client';
describe('API client', () => {
  afterEach(() => vi.unstubAllGlobals());
  it('retains an error response status', () => { expect(new ApiError(503, 'unavailable').status).toBe(503); });
  it('includes cookies on API requests without changing the health contract', async () => { const fetch = vi.fn().mockResolvedValue(new Response(JSON.stringify({ status: 'ok', service: 'api', timestamp: new Date().toISOString() }), { status: 200, headers: { 'Content-Type': 'application/json' } })); vi.stubGlobal('fetch', fetch); await api.health(); expect(fetch).toHaveBeenCalledWith(expect.stringContaining('/health'), expect.objectContaining({ credentials: 'include' })); });
  it('adds only the selected variant and quantity', async () => { const fetch = vi.fn().mockResolvedValue(new Response(JSON.stringify({ items: [], subtotal: 0, totalQuantity: 0 }), { status: 200 })); vi.stubGlobal('fetch', fetch); await cartApi.add({ variantId: 'cm12345678901234567890123', quantity: 2 }); expect(fetch).toHaveBeenCalledWith(expect.stringContaining('/cart/items'), expect.objectContaining({ method: 'POST', credentials: 'include', body: JSON.stringify({ variantId: 'cm12345678901234567890123', quantity: 2 }) })); });
  it('submits guest checkout details without cart items or prices', async () => { const payload = { contact: { name: 'Rafi Ahmed', email: 'r@example.com', phone: '01712345678' }, shippingAddress: { recipientName: 'Rafi Ahmed', phone: '01712345678', addressLine: 'Road 1', cityDistrict: 'Dhaka', country: 'BD' }, shippingMethod: 'STANDARD' as const, paymentMethod: 'CASH_ON_DELIVERY' as const }; const response = { orderNumber: 'RAQI-1', status: 'PENDING', paymentStatus: 'UNPAID', paymentMethod: 'CASH_ON_DELIVERY', currency: 'BDT', subtotal: 100, shippingAmount: 120, total: 220, createdAt: new Date().toISOString(), contact: payload.contact, shippingAddress: { ...payload.shippingAddress, area: null, postalCode: null }, shippingMethod: { code: 'STANDARD', name: 'Standard delivery' }, items: [] }; const fetch = vi.fn().mockResolvedValue(new Response(JSON.stringify(response), { status: 200 })); vi.stubGlobal('fetch', fetch); await checkoutApi.place(payload); expect(fetch).toHaveBeenCalledWith(expect.stringContaining('/checkout'), expect.objectContaining({ credentials: 'include', body: JSON.stringify(payload) })); });
  it('uses credentialed customer order endpoints', async () => { const fetch = vi.fn().mockResolvedValue(new Response(JSON.stringify({ data: [] }), { status: 200 })); vi.stubGlobal('fetch', fetch); await ordersApi.list(); expect(fetch).toHaveBeenCalledWith(expect.stringContaining('/orders'), expect.objectContaining({ credentials: 'include' })); });
});
